[appendix]
:appendix-caption: Annex
== Usage with SensorML (Informative)

=== Introduction

The OGC Sensor Model Language (SensorML) standard provides the means of semantically defining processes and their associated components with the measurement and post-measurement transformation of observations. Whereas the standard provides the means to describe sensor characteristics, it allows implementations to use their own identifiers for referencing their sensor characteristics. This enables interoperability by allowing the sensor characteristics to be described in a consistent syntax, however it also requires that applications attempting to interpret the sensor model descriptions understand the meaning of the identifiers before hand.

=== Examples

The following is an example of how to use OGC-registered ISO URIs with SensorML.

[source,xml]
----

<sml:SimpleProcess gml:id="example.1"
xmlns:sml="http://www.opengis.net/sensorml/2.0"
xmlns:swe="http://www.opengis.net/swe/2.0"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xlink="http://www.w3.org/1999/xlink"
xsi:schemaLocation="http://www.opengis.net/sensorml/2.0 http://schemas.opengis.net/sensorML/2.0/sensorML.xsd"
definition="http://www.opengis.net/def/sensor-model/ISO/0/ISO-19130/SD_SensorModel/trueReplacementModel/SD_TrueReplacementModel">
    <sml:parameters>
        <sml:ParameterList>
            <sml:parameter name="regionOfValidity">
                <swe:DataRecord definition="http://www.opengis.net/def/sensor-model-param/ISO/0/ISO-19130/SD_TrueReplacementModel/regionOfValidity">
                    <swe:label>True Replacement Model regionOfValidity</swe:label>
                    <swe:field name="gridPoints">
                       <swe:Vector referenceFrame="http://www.opengis.net/def/cs/OGC/0/CartesianIndexed2D">
                          <swe:coordinate name="gridPoint1">
                             <swe:Quantity definition="http://www.opengis.net/ont/gml#Point">
                                <swe:uom code="GridSpacing"/>
                             </swe:Quantity>
                          </swe:coordinate>
                          <swe:coordinate name="gridPoint2">
                             <swe:Quantity definition="http://www.opengis.net/ont/gml#Point">
                                <swe:uom code="GridSpacing"/>
                             </swe:Quantity>
                          </swe:coordinate>
                          <swe:coordinate name="gridPoint3">
                             <swe:Quantity definition="http://www.opengis.net/ont/gml#Point">
                                <swe:uom code="GridSpacing"/>
                             </swe:Quantity>
                          </swe:coordinate>
                          <swe:coordinate name="gridPoint4">
                             <swe:Quantity definition="http://www.opengis.net/ont/gml#Point">
                                <swe:uom code="GridSpacing"/>
                             </swe:Quantity>
                          </swe:coordinate>
                       </swe:Vector>
                    </swe:field>
                </swe:DataRecord>
            </sml:parameter>
        </sml:ParameterList>
    </sml:parameters>
</sml:SimpleProcess>



----

The following is an example of how to use OGC-registered NITF URIs with SensorML.

[source,xml]
----
<sml:SimpleProcess gml:id="example.2"
xmlns:sml="http://www.opengis.net/sensorml/2.0"
xmlns:swe="http://www.opengis.net/swe/2.0"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xlink="http://www.w3.org/1999/xlink"
xsi:schemaLocation="http://www.opengis.net/sensorml/2.0 http://schemas.opengis.net/sensorML/2.0/sensorML.xsd"
definition="http://www.opengis.net/def/sensor-model/NTB/2.1/NITF/SENSRB">
    <sml:parameters>
        <sml:ParameterList>
            <sml:parameter name="sensrbParams">
                <swe:DataRecord definition="http://www.opengis.net/def/sensor-model-param/NTB/2.1/NITF/SENSRB/">
                    <swe:label>NITF SENSRB Sensor Model Parameters (subset of)</swe:label>
                    <swe:field name="referenceRow">
                        <swe:Quantity definition="http://www.opengis.net/def/sensor-model-param/NTB/2.1/NITF/SENSRB/REFERENCE_ROW">
                            <swe:label>Reference Row</swe:label>
                            <swe:uom code="pixel"/>
                        </swe:Quantity>
                    </swe:field>
                    <swe:field name="SENSOR_CALIBRATION_DATA">
                        <swe:DataRecord>
                            <swe:label>Sensor Calibration Data</swe:label>
                            <swe:field name="PRINCIPAL_POINT_OFFSET_X">
                                <swe:Quantity definition="http://www.opengis.net/def/sensor-model-param/NTB/2.1/NITF/SENSRB/SENSOR_CALIBRATION_DATA/PRINCIPAL_POINT_OFFSET_X">
                                    <swe:label>PRINCIPAL_POINT_OFFSET_X</swe:label>
                                    <swe:uom code="pixel"/>
                                </swe:Quantity>
                            </swe:field>
                            <swe:field name="PRINCIPAL_POINT_OFFSET_Y">
                                <swe:Quantity definition="http://www.opengis.net/def/sensor-model-param/NTB/2.1/NITF/SENSRB/SENSOR_CALIBRATION_DATA/PRINCIPAL_POINT_OFFSET_Y">
                                    <swe:label>PRINCIPAL_POINT_OFFSET_Y</swe:label>
                                    <swe:uom code="pixel"/>
                                </swe:Quantity>
                            </swe:field>
                        </swe:DataRecord>
                    </swe:field>
                </swe:DataRecord>
            </sml:parameter>
        </sml:ParameterList>
    </sml:parameters>
</sml:SimpleProcess>

----
