== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== *Observation*
Act of observing a property or phenomenon [ISO 19156, definition 4.10]
Note: The goal of an observation may be to measure, estimate or otherwise determine the value of a property.

=== *Sensor*
An entity capable of observing a phenomenon and returning an observed value. Type of observation procedure that provides the estimated value of an observed property at its output. Note: A sensor uses a combination of physical, chemical or biological means in order to estimate the underlying observed property. At the end of the measuring chain electronic devices often produce signals to be processed. (OGC 12-000)

=== *Sensor Model*
A geopositioning mathematical description of the relationship between the three-dimensional object space and the two-dimensional plane of the associated image produced by a sensor (ISO/TS 19130)

=== *(Sensor) Platform*
An entity to which can be attached sensors or other platforms. A platform has an associated local coordinate reference frame that can be referenced relative to an external coordinate reference frame and to which the reference frames of attached sensors and platforms can be referenced.(OGC 12-000)
