== Name Assignment Policy

=== Sensor Models

The register of sensor models http://www.opengis.net/register/ogc-na/sensor-model is controlled by OGC-NA. Changes to this register (additions, deletions, and supersession) shall be initiated by a submission to the OGC Naming Authority names@opengeospatial.org.

Any relevant stakeholder (OGC member or non-OGC member) may submit proposals for changes.

=== Sensor Model Parameters

The register of sensor model parameters http://www.opengis.net/register/ogc-na/sensor-model-param is controlled by OGC-NA. Changes to this register (additions, deletions, and supersession) shall be initiated by a submission to the OGC Naming Authority names@opengeospatial.org.

Any relevant stakeholder (OGC member or non-OGC member) may submit proposals for changes.

=== Description

Each sensor model parameter shall be described using the Simple Knowledge Organization System (SKOS) vocabulary of the World Wide Web (W3C) consortium. Other vocabularies may also be used *in addition* to SKOS, for example the OGC Semantic Registry Information Model (SRIM) cite:[Fellah2017].

The following predicates are mandatory for describing sensor model and parameter resources:

* *skos:prefLabel* for providing a human-readable version of a resource's name
* *dcterms:created* for stating the date the resource was created in the register
* *dcterms:modified* for stating the date the resource was modified in the register (mandatory if the resource has been modified)
* *policy:status* for indicating whether the resource is valid, retired, superseded, or under consideration
* *skos:definition* for providing a human-readable description of the resource
* *skos:inScheme* for stating the Concept Scheme to which the resource belongs
* *rdfs:label* for providing a human-readable version of a resource's name (used for compatibility with non-SKOS systems)


An example of the use of the above-listed predicates is presented below in the Turtle format of the Resource Description Framework (RDF). Note that individual sensor model parameters are described as instances of the SKOS Concept class, whereas sensor models are described as instances of the SKOS ConceptScheme class.

[source,ttl]
----
<http://www.opengis.net/def/sensor-model/NTB/2.1/NITF/RPC00B>
        a                 skos:ConceptScheme ;
        rdfs:label        "NITF Rapid Positioning Capability" ;
        dcterms:created   "2018-03-13"^^<http://www.w3.org/2001/XMLSchema#date> ;
        dcterms:modified  "2018-04-16"^^<http://www.w3.org/2001/XMLSchema#date> ;
        policy:status     status:valid ;
        skos:definition   "The sensor model supported by the RPC00B extension of the NITF standard contains rational function polynomial coefficients and normalization parameters that define the physical relationship between image coordinates and ground coordinates." ;
        skos:prefLabel    "NITF Rapid Positioning Capability" ;
        skos:broader     <http://www.opengis.net/def/sensor-model/OGC/0/RationalPolynomialCoefficients> .


<http://www.opengis.net/def/sensor-model-param/NTB/2.1/NITF/RPC00B/LINE_OFF>
        a                 skos:Concept ;
        rdfs:label        "Line Offset" ;
        dcterms:created   "2018-03-13"^^<http://www.w3.org/2001/XMLSchema#date> ;
        dcterms:modified  "2018-04-16"^^<http://www.w3.org/2001/XMLSchema#date> ;
        policy:status     status:valid ;
        skos:definition   "Line Offset" ;
        skos:inScheme     <http://www.opengis.net/def/sensor-model/NTB/2.1/NITF/RPC00B> ;
        skos:prefLabel    "Line Offset" .


----

Note the use of the SKOS *broader* predicate to represent the relationship of the sensor model adopted by RPC00B to the Rational Polynomial Coefficients model cite:[Guo2006].
