== References

IETF: RFC 2141 URN Syntax  http://tools.ietf.org/html/rfc2141 (1997)

IETF: RFC 2616 Hypertext Transfer Protocol -- HTTP/1.1  http://tools.ietf.org/html/rfc2616 (1999)

IETF: RFC 3986 Uniform Resource Identifier (URI): Generic Syntax http://tools.ietf.org/html/rfc3986 (2005)

IETF: RFC 4395 Guidelines and Registration Procedures for New URI Schemes  http://tools.ietf.org/html/rfc4395 (2006)

IETF: RFC 5141 A Uniform Resource Name (URN) Namespace for the International Organization for Standardization (ISO)  http://tools.ietf.org/html/rfc5141 (2008)

IETF: RFC 5165 A Uniform Resource Name (URN) Namespace for the Open Geospatial Consortium (OGC)  http://tools.ietf.org/html/rfc5165 (2008)

IETF: RFC 5234 Augmented BNF for Syntax Specifications: ABNF  http://tools.ietf.org/html/rfc5234 (2008)

ISO: ISO/TS 19130, Geographic information - Imagery sensor models for geopositioning, https://www.iso.org/obp/ui/#iso:std:iso:ts:19130:ed-1:v1:en (2010)

ISO: ISO/TS 19130-2, Geographic information — Imagery sensor models for geopositioning — Part 2: SAR, InSAR, lidar and sonar, https://www.iso.org/obp/ui/#iso:std:iso:ts:19130:-2:ed-1:v1:en (2014)

OGC: OGC 05-020r25, Technical Committee Policies and Procedures http://docs.opengeospatial.org/pol/05-020r25/05-020r25.html (2017)

OGC: OGC 09-046r2, OGC Naming Authority – Procedures http://portal.opengeospatial.org/files/?artifact_id=37800 (2010)

OGC: OGC 09-048r3, OGC-NA Name type specification - definitions: Part 1 - basic name' http://portal.opengeospatial.org/files/?artifact_id=37802 (2010)

OGC: OGC 12-000, OGC® SensorML: Model and XML Encoding Standard https://portal.opengeospatial.org/files/?artifact_id=55939

NITFS Technical Board: NITF 2.1., National Imagery Transmission Format Version 2.1 MIL-STD-2500C

NITFS Technical Board: Appendix E - Airborne Support Data Extensions (ASDE) VERSION 2.1, STDI-0002 App E (2000)

NITFS Technical Board: APPENDIX Z - General Electro-Optical (Visible, Infrared, Multi- and Hyperspectral) Sensor Parameters (SENSRB) Tagged Record Extension (TRE) VERSION 2.1, STDI-0002 App Z (2013)

W3C: Simple Knowledge Organization System (SKOS) https://www.w3.org/TR/2009/REC-skos-reference-20090818 (2009)
