#curl -o crs/README.md  http://www.opengis.net/def/crs/
#curl -o crs/OGC/README.md  http://www.opengis.net/def/crs/OGC/
#curl -o crs/OGC/0/README.md  http://www.opengis.net/def/crs/OGC/0/
#curl -o crs/OGC/0/_Temporal_template  http://www.opengis.net/def/crs/OGC/0/_Temporal_template
#curl -o crs/OGC/0/Temporal http://www.opengis.net/def/crs/OGC/0/Temporal
#curl -o crs/OGC/0/_AnsiDate_template http://www.opengis.net/def/crs/OGC/0/_AnsiDate_template
#curl -o crs/OGC/0/_ChronometricGeologicTime_template http://www.opengis.net/def/crs/OGC/0/_ChronometricGeologicTime_template
#curl -o crs/OGC/0/_JulianDate_template http://www.opengis.net/def/crs/OGC/0/_JulianDate_template
#curl -o crs/OGC/0/_TruncatedJulianDate_template http://www.opengis.net/def/crs/OGC/0/_TruncatedJulianDate_template
#curl -o crs/OGC/0/AnsiDate http://www.opengis.net/def/crs/OGC/0/AnsiDate
#curl -o crs/OGC/0/ChronometricGeologicTime http://www.opengis.net/def/crs/OGC/0/ChronometricGeologicTime
#curl -o crs/OGC/0/JulianDate http://www.opengis.net/def/crs/OGC/0/JulianDate
#curl -o crs/OGC/0/TruncatedJulianDate http://www.opengis.net/def/crs/OGC/0/TruncatedJulianDate
#curl -o crs/OGC/0/UnixTime http://www.opengis.net/def/crs/OGC/0/UnixTime
#curl -o crs/OGC/0/_Index1D_template http://www.opengis.net/def/crs/OGC/0/_Index1D_template
#curl -o crs/OGC/0/_Index2D_template http://www.opengis.net/def/crs/OGC/0/_Index2D_template
#curl -o crs/OGC/0/_Index3D_template http://www.opengis.net/def/crs/OGC/0/_Index3D_template
#curl -o crs/OGC/0/_Index4D_template http://www.opengis.net/def/crs/OGC/0/_Index4D_template
#curl -o crs/OGC/0/_Index5D_template http://www.opengis.net/def/crs/OGC/0/_Index5D_template
#curl -o crs/OGC/0/Index1D http://www.opengis.net/def/crs/OGC/0/Index1D
#curl -o crs/OGC/0/Index2D http://www.opengis.net/def/crs/OGC/0/Index2D
#curl -o crs/OGC/0/Index3D http://www.opengis.net/def/crs/OGC/0/Index3D
#curl -o crs/OGC/0/Index4D http://www.opengis.net/def/crs/OGC/0/Index4D
#curl -o crs/OGC/0/Index5D http://www.opengis.net/def/crs/OGC/0/Index5D
#curl -o crs/OGC/0/_UnixTime_template http://www.opengis.net/def/crs/OGC/0/_UnixTime_template
#curl -o crs/OGC/0/CRS84h http://www.opengis.net/def/crs/OGC/0/CRS84h
#curl -o crs/OGC/0/ECI_GCRF http://www.opengis.net/def/crs/OGC/0/ECI_GCRF
#curl -o crs/OGC/0/DATUM_GCRF http://www.opengis.net/def/crs/OGC/0/DATUM_GCRF
#curl -o crs/OGC/0/ECI_J2000 http://www.opengis.net/def/crs/OGC/0/ECI_J2000
#curl -o crs/OGC/0/DATUM_J2000 http://www.opengis.net/def/crs/OGC/0/DATUM_J2000
#curl -o crs/OGC/0/ECI_M50 http://www.opengis.net/def/crs/OGC/0/ECI_M50
#curl -o crs/OGC/0/DATUM_M50 http://www.opengis.net/def/crs/OGC/0/DATUM_M50
#curl -o crs/OGC/1.3/README.md http://www.opengis.net/def/crs/OGC/1.3/
#curl -o crs/OGC/1.3/CRS1 http://www.opengis.net/def/crs/OGC/1.3/CRS1
#curl -o crs/OGC/1.3/CRS27 http://www.opengis.net/def/crs/OGC/1.3/CRS27
#curl -o crs/OGC/1.3/CRS83 http://www.opengis.net/def/crs/OGC/1.3/CRS83
#curl -o crs/OGC/1.3/CRS84 http://www.opengis.net/def/crs/OGC/1.3/CRS84
#curl -o crs/OGC/1.3/_AUTO42001_template http://www.opengis.net/def/crs/OGC/1.3/_AUTO42001_template
#curl -o crs/OGC/1.3/AUTO42001 http://www.opengis.net/def/crs/OGC/1.3/AUTO42001
#curl -o crs/OGC/1.3/_AUTO42002_template http://www.opengis.net/def/crs/OGC/1.3/_AUTO42002_template
#curl -o crs/OGC/1.3/_AUTO42003_template http://www.opengis.net/def/crs/OGC/1.3/_AUTO42003_template
#curl -o crs/OGC/1.3/AUTO42003 http://www.opengis.net/def/crs/OGC/1.3/AUTO42003
#curl -o crs/OGC/1.3/_AUTO42004_template http://www.opengis.net/def/crs/OGC/1.3/_AUTO42004_template
#curl -o crs/OGC/1.3/AUTO42004 http://www.opengis.net/def/crs/OGC/1.3/AUTO42004
#curl -o crs/OGC/1.3/AUTO42002 http://www.opengis.net/def/crs/OGC/1.3/AUTO42002
#curl -o axis/OGC/0/tcs http://www.opengis.net/def/axis/OGC/0/tcs
#curl -o axis/OGC/0/days http://www.opengis.net/def/axis/OGC/0/days
#curl -o axis/OGC/0/mya http://www.opengis.net/def/axis/OGC/0/mya
#curl -o axis/OGC/0/seconds http://www.opengis.net/def/axis/OGC/0/seconds
#curl -o axis/OGC/0/indexed http://www.opengis.net/def/axis/OGC/0/indexed
#curl -o axis/OGC/0/ECI-X http://www.opengis.net/def/axis/OGC/0/ECI-X
#curl -o axis/OGC/0/ECI-Y http://www.opengis.net/def/axis/OGC/0/ECI-Y
#curl -o axis/OGC/0/ECI-Z http://www.opengis.net/def/axis/OGC/0/ECI-Z
#curl -o axis/OGC/0/ENU-X http://www.opengis.net/def/axis/OGC/0/ENU-X
#curl -o axis/OGC/0/ENU-Y http://www.opengis.net/def/axis/OGC/0/ENU-Y
#curl -o axis/OGC/0/ENU-Z http://www.opengis.net/def/axis/OGC/0/ENU-Z
#curl -o axis/OGC/0/NED-X http://www.opengis.net/def/axis/OGC/0/NED-X
#curl -o axis/OGC/0/NED-Y http://www.opengis.net/def/axis/OGC/0/NED-Y
#curl -o axis/OGC/0/NED-Z http://www.opengis.net/def/axis/OGC/0/NED-Z
#curl -o axis/OGC/0/README.md http://www.opengis.net/def/axis/OGC/0/
#curl -o axis/OGC/README.md http://www.opengis.net/def/axis/OGC/
#curl -o axis/README.md http://www.opengis.net/def/axis/
#curl -o coordinateOperation/OGC/1.3/_AutoUniversalTransverseMercatorConversion_template http://www.opengis.net/def/coordinateOperation/OGC/1.3/_AutoUniversalTransverseMercatorConversion_template
#curl -o coordinateOperation/OGC/1.3/AutoUniversalTransverseMercatorConversion http://www.opengis.net/def/coordinateOperation/OGC/1.3/AutoUniversalTransverseMercatorConversion
#curl -o coordinateOperation/OGC/1.3/_AutoTransverseMercatorConversion_template http://www.opengis.net/def/coordinateOperation/OGC/1.3/_AutoTransverseMercatorConversion_template
#curl -o coordinateOperation/OGC/1.3/AutoTransverseMercatorConversion http://www.opengis.net/def/coordinateOperation/OGC/1.3/AutoTransverseMercatorConversion
#curl -o coordinateOperation/OGC/1.3/_AutoOrthographicConversion_template http://www.opengis.net/def/coordinateOperation/OGC/1.3/_AutoOrthographicConversion_template
#curl -o coordinateOperation/OGC/1.3/AutoOrthographicConversion http://www.opengis.net/def/coordinateOperation/OGC/1.3/AutoOrthographicConversion
#curl -o coordinateOperation/OGC/1.3/_AutoEquirectangularConversion_template http://www.opengis.net/def/coordinateOperation/OGC/1.3/_AutoEquirectangularConversion_template
#curl -o coordinateOperation/OGC/1.3/AutoEquirectangularConversion http://www.opengis.net/def/coordinateOperation/OGC/1.3/AutoEquirectangularConversion
#curl -o coordinateOperation/OGC/1.3/README.md http://www.opengis.net/def/coordinateOperation/OGC/1.3/
#curl -o coordinateOperation/OGC/README.md http://www.opengis.net/def/coordinateOperation/OGC/
#curl -o coordinateOperation/README.md http://www.opengis.net/def/coordinateOperation/
#curl -o cs/OGC/0/tcs http://www.opengis.net/def/cs/OGC/0/tcs
#curl -o cs/OGC/0/Days http://www.opengis.net/def/cs/OGC/0/Days
#curl -o cs/OGC/0/Mya http://www.opengis.net/def/cs/OGC/0/Mya
#curl -o cs/OGC/0/Seconds http://www.opengis.net/def/cs/OGC/0/Seconds
#curl -o cs/OGC/0/CartesianIndexed1D http://www.opengis.net/def/cs/OGC/0/CartesianIndexed1D
#curl -o cs/OGC/0/CartesianIndexed2D http://www.opengis.net/def/cs/OGC/0/CartesianIndexed2D
#curl -o cs/OGC/0/CartesianIndexed3D http://www.opengis.net/def/cs/OGC/0/CartesianIndexed3D
#curl -o cs/OGC/0/CartesianIndexed4D http://www.opengis.net/def/cs/OGC/0/CartesianIndexed4D
#curl -o cs/OGC/0/CartesianIndexed5D http://www.opengis.net/def/cs/OGC/0/CartesianIndexed5D
#curl -o cs/OGC/0/ECI http://www.opengis.net/def/cs/OGC/0/ECI
#curl -o cs/OGC/0/ENU http://www.opengis.net/def/cs/OGC/0/ENU
#curl -o cs/OGC/0/NED http://www.opengis.net/def/cs/OGC/0/NED
#curl -o cs/OGC/0/README.md http://www.opengis.net/def/cs/OGC/0/
#curl -o cs/OGC/README.md http://www.opengis.net/def/cs/OGC/
#curl -o cs/README.md http://www.opengis.net/def/cs/
#curl -o cs/OGC/1.3/MapCS http://www.opengis.net/def/cs/OGC/1.3/MapCS
#curl -o cs/OGC/1.3/README.md http://www.opengis.net/def/cs/OGC/1.3/
#curl -o datum/OGC/0/TDatum http://www.opengis.net/def/datum/OGC/0/TDatum
#curl -o datum/OGC/0/AnsiDateDatum http://www.opengis.net/def/datum/OGC/0/AnsiDateDatum
#curl -o datum/OGC/0/JulianDateDatum http://www.opengis.net/def/datum/OGC/0/JulianDateDatum
#curl -o datum/OGC/0/TruncatedJulianDateDatum http://www.opengis.net/def/datum/OGC/0/TruncatedJulianDateDatum
#curl -o datum/OGC/0/UnixTimeDatum http://www.opengis.net/def/datum/OGC/0/UnixTimeDatum
#curl -o datum/OGC/0/YearZeroDatum http://www.opengis.net/def/datum/OGC/0/YearZeroDatum
#curl -o datum/OGC/0/CellCenter http://www.opengis.net/def/datum/OGC/0/CellCenter
#curl -o datum/OGC/1.0/ComputerDisplay http://www.opengis.net/def/datum/OGC/1.0/ComputerDisplay
#curl -o datum/OGC/1.0/README.md http://www.opengis.net/def/datum/OGC/1.0/
#curl -o datum/OGC/0/README.md http://www.opengis.net/def/datum/OGC/0/
#curl -o datum/OGC/README.md http://www.opengis.net/def/datum/OGC/
#curl -o datum/README.md http://www.opengis.net/def/datum/
