
////
== Keywords

Keywords inserted here automatically by Metanorma
////


.Preface

This document describes the procedures used by the OGC Naming Authority for the registration of OGC Standards Building Blocks.

////
*OGC Declaration*
////

////
[THIS TEXT IS ALREADY ADDED AUTOMATICALLY IN THE FRONTISPIECE OF ALL OGC DOUCMENTS]

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
////



[abstract]
== Abstract

The mission of the OGC Naming Authority (OGC-NA) is to provide the means through which OGC resources such as OGC documents, namespaces and ontologies can be controlled and managed such that they can provide clear and well-defined names and definitions. In the terminology defined in ISO 19135, OGC-NA is the Control Body for the register of OGC Names. This document describes the framework of documents, registers and other resources required for OGC-NA to execute that role.

[.preface]
== Security Considerations

//If no security considerations have been made for this Standard, use the following text.

No security considerations have been made for this Standard.

////
If security considerations have been made for this Standard, follow the examples found in IANA or IETF documents. Please see the following example.

“VRRP is designed for a range of internetworking environments that may employ different security policies. The protocol includes several authentication methods ranging from no authentication, simple clear text passwords, and strong authentication using IP Authentication with MD5 HMAC. The details on each approach including possible attacks and recommended environments follows.

Independent of any authentication type VRRP includes a mechanism (setting TTL=255, checking on receipt) that protects against VRRP packets being injected from another remote network. This limits most vulnerabilities to local attacks.
NOTE: The security measures discussed in the following sections only provide various kinds of authentication. No confidentiality is provided at all. This should be explicitly described as outside the scope....”
////

////
== Submitting organizations

Submitting organisations added automatically by Metanorma from document attributes
////

[.preface]
== Submitters
All questions regarding this submission should be directed to the editor or the submitters:


|===
|Name |Affiliation

|Gobe Hobona | OGC 
|TBA | TBA
|TBA | TBA
|TBA | TBA
|TBA | TBA
|===


[.preface]
== Contributors

//This clause is optional.

Additional contributors to this Standard include the following:

Individual name(s), Organization

[NOTE]
====
If you need to place any further sections in the preface area
use the `[.preface]` attribute.
====

