
== Scope

Clause 7.2.1 of the OGC Technical Committee's Policies and Procedures (https://docs.ogc.org/pol/05-020r29/05-020r29.html[OGC 05-020r29]) defines a Standard Building Block as follows:

"Many OGC Standards are structured with modular sets of requirements (or requirement classes) that collectively function as a reusable building block. There is no firm definition for the content or scope of a building block, but the building block must fulfill a function that can operate in the larger context of an implementation, including combination with other OGC building blocks to create novel implementations.

Building blocks developed for one Standard can be reused in another Standard. To facilitate such reuse, a Standard constructed of building blocks shall identify each building block and publish a definition of the building block to OGC's Registries and web resources. The definition will be in the form most suitable for the type of building block (e.g., Open API for a Standardized API), reference the owning Standard, and be adequately documented to be used in reference.

OGC Standards that reuse building blocks from other Standards must include in the Normative References a reference to the owning Standard of the building block(s) and a direct reference to the registered building block(s) content. In this fashion, implementers of the Standard reusing these building blocks need to only access specific parts (the building blocks) of the referenced Standard, not the entire document."

NOTE: The planned revision of "The Specification Model — A Standard for Modular specifications" (https://portal.ogc.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the ModSpec, is expected to include a more precise definition of a Standards Building Block.

In addition to the Clause reproduced above, https://portal.ogc.org/public_ogc/directives/directives.php#51[Policy Directive 51] states the following in relation to OGC API - Common.

"New capabilities (building blocks) to be inserted into OGC API – Common as new Parts (multiple building blocks can be included in a single Part).

New Parts can only be voted by the TC/PC after approval by all OGC API SWGs.

Movement of a building block from an approved OGC API Standard to OGC API - Common results in that building block being duplicated (present in both Standards) until a Major revision is made to the originating OGC API."

