
== Scope

This OGC Policy specifies the governance rules and procedures for the registration of OGC Standards Building Blocks. The policy can be considered a profile of https://docs.ogc.org/pol/09-046r6.html[OGC 09-046r6], OGC Naming Authority - Procedures policy.

Clause 7.2.1 of the OGC Technical Committee's Policies and Procedures (https://docs.ogc.org/pol/05-020r29/05-020r29.html[OGC 05-020r29]) defines a Standard Building Block as follows:

__"Many OGC Standards are structured with modular sets of requirements (or requirement classes) that collectively function as a reusable building block. There is no firm definition for the content or scope of a building block, but the building block must fulfill a function that can operate in the larger context of an implementation, including combination with other OGC building blocks to create novel implementations.

Building blocks developed for one Standard can be reused in another Standard. To facilitate such reuse, a Standard constructed of building blocks shall identify each building block and publish a definition of the building block to OGC's Registries and web resources. The definition will be in the form most suitable for the type of building block (e.g., Open API for a Standardized API), reference the owning Standard, and be adequately documented to be used in reference.

OGC Standards that reuse building blocks from other Standards must include in the Normative References a reference to the owning Standard of the building block(s) and a direct reference to the registered building block(s) content. In this fashion, implementers of the Standard reusing these building blocks need to only access specific parts (the building blocks) of the referenced Standard, not the entire document."__

NOTE: The planned revision of "The Specification Model — A Standard for Modular specifications" (https://portal.ogc.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the ModSpec, is expected to include a more precise definition of a Standards Building Block.



