[[terms_and_definitions]]
== Terms definitions and abbreviated terms

=== Terms and definitions

==== conformance test

test, abstract or real, of one or more requirements contained within a standard, or set of standards (source: https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3])

====  conformance test class

set of conformance test modules that must be applied to receive a single certificate of conformance (source: https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3])

NOTE: When no ambiguity is possible, the word "test" may be left out, so conformance test class maybe called a *conformance class*.


====  requirement

expression in the content of a document conveying criteria to be fulfilled if compliance with the document is to be claimed and from which no deviation is permitted (source: https://www.iso.org/sites/directives/current/part2/index.xhtml[ISO/IEC Directives Part 2])

====  requirements class

aggregate of all requirement modules that must all be satisfied to satisfy a conformance test class (source: https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3])

NOTE: There is some confusion possible here, since the testing of indirect dependencies seems to violate this definition. But the existence of an indirect dependency implies that the test is actually a test of the existence of the relationship from the original target to something that has a property (satisfies a condition or requirement from another requirements class).
