[[considerations]]
== Considerations for Registration

=== Granularity

OGC Standards are composed of specification elements as defined in the OGC Standard for Modular specifications (OGC 08-131r3), also known as the ModSpec. These specification elements include requirements classes, requirements, conformance classes, and abstract tests. Each one of these specification elements may reference other constructs or artifacts such as schema documents, schema fragments, parameters, API definition documents, or others. Those constructs or artifacts may themselves reference others. Therefore, a key consideration for the registration of Standards Building Blocks is at what level of granularity a building block should be registered. The following are the levels of granularity that may be considered for registration.

==== Level 1: Conformance Classes and Requirements Classes

TBA

==== Level 2: Requirements and Abstract Tests

TBA

==== Level 3: Schema documents and API definition documents

TBA

==== Level 4: Schema fragments and Parameters

TBA