[[processes]]
== Processes

=== Review by the OAB

During the OAB review of the Standard, it is the responsibility of the SWG to seek a recommendation from the OAB on the granularity of the building block.

Trigger: SWG submits a candiate Standard or a previously approved Standard for OAB review.

Inputs: 

* candiate Standard or a previously approved Standard

Process:

. TBA
. TBA
. TBA

Outputs:

* Recommendation from the OAB on the granularity of the building block

=== Approval for registration

Trigger: SWG submits a TC-approved Standard for registration as building blocks.

Inputs: 

* Approved and publish Standard
* Recommendation from the OAB on the granularity of the building block

Process:

. OGC-NA Chair shall begin a period of review by the OGC-NA
. OGC-NA Chair shall conduct a vote on registration of the building block or as a group of building blocks
. If the vote passes, OGC Staff shall register the building block or group of building blocks in the register.
. If the vote fails to pass, then OGC-NA Chair shall ask the SWG to revise the proposal before resubmission.

Outputs:

* Registered Building Block displayed on the registry


=== Appeals

TBA