[[processes]]
== Processes

=== Review by the OGC Architecture Board

Each OGC candidate Standard goes through a series of stages on the way to approval by the TC. One of those stages is the review by the OGC Architecture Board (OAB).

The mission of the OAB is to provide a forum within which Consortium wide standards architecture and life cycle management issues can be discussed and deliberated with the intent of providing guidance and recommendations to the Technical Committee (TC) and the Executive Planning Committee (EPC) on these issues. 

During the OAB's review of a Standard, it is the responsibility of the SWG to seek a recommendation from the OAB on the granularity of the building block.

Trigger: SWG submits a candiate Standard or a previously approved Standard for OAB review.

Inputs: 

* candidate Standard or a previously approved Standard

Process:

. OAB Chair begins a period of review by the OAB
. OAB Members propose options for an appropriate level of granularity
. OAB Chair conducts a vote on on the preferred level of granularity of the building blocks to be registered
. OAB Chair creates a ticket, on the OGC-NA Git repository, with a recommendation from the OAB on the level of granularity of the building block to be registered

Outputs:

* Recommendation from the OAB on the granularity of the building block

=== Approval for registration

Trigger: SWG submits a TC-approved Standard for registration as building blocks.

Inputs: 

* Approved and published Standard
* Recommendation from the OAB on the granularity of the building block

Process:

. OGC-NA Chair begins a period of review by the OGC-NA
. OGC-NA Chair conducts a vote on registration of the building block or as a group of building blocks
. If the vote passes, OGC Staff register the building block or group of building blocks in the register.
. If the vote fails to pass, then OGC-NA Chair asks the SWG to revise the proposal before resubmission.

Outputs:

* Registered Building Block displayed on the registry


=== Appeals

A SWG may appeal to the TC Chair if it disagrees with the decision of the OAB regarding the recommended level granularity of the building block registration. 

Inputs:

* An Appeal Request Form

Process:

. SWG submits appeal form to the TC Chair
. TC Chair discusses the appeal with the OAB
. OAB invites the SWG to discuss the appeal at OAB meeting co-chaired by TC Chair
. OAB conducts a second vote on a recommendation for the level of granularity for registering the building blocks

Outputs:

* Final decision of the OAB

The Appeal Request Form shall contain at a minimum:

* identification of the source of the appeal (i.e. the SWG and the point of contact),
* a detailed and specific description of the situation, 
* a justification for the appeal, and
* a statement of the impact if the appeal is not successful

