[[considerations]]
== Considerations for Registration

OGC Standards are composed of specification elements as defined in the OGC Standard for Modular specifications (OGC 08-131r3), also known as the ModSpec. These specification elements include requirements classes, requirements, conformance classes, and abstract tests. Each one of these specification elements may reference other constructs or artifacts such as schema documents, schema fragments, parameters, API definition documents, or others. Those constructs or artifacts may themselves reference others. Therefore, the following factors shall be considered during the review of a proposal to register a building block.

This section presents requirements for reviewers involved the Architecture DWG approval of building blocks.

.Requirements for Architecture DWG approval of building blocks
[cols=",",options="header"]
|===
|Ref. |Description
|1 | The level of granularity of a building block SHALL only be approved if its definition is equal to or smaller than that of its originating Conformance Class or Requirements Class.
|2 | The reusability of a building block SHALL only be approved if the building block can be shown to usable by two or more OGC Standards.
|3 | The interfacing of a building block SHALL only be approved if it is well defined in the source Standard.
|===

This section presents requirements for reviewers involved the OGC-NA approval of building blocks.

.Requirements for reviewers involved in OGC-NA approval of building blocks
[cols=",",options="header"]
|===
|Ref. |Description
|1 | The description of a building block SHALL only be approved if the description matches that specified in the originating OGC Standards.
|2 | The identification of a building block SHALL only be approved if the identification matches that specified in the originating OGC Standards. This includes the case format and pattern of the name of the building block.
|===
