[[processes]]
== Processes

=== Review by the OGC Architecture Board

Each OGC candidate Standard goes through a series of stages on the way to approval by the TC. One of those stages is the review by the OGC Architecture Board (OAB).

The mission of the OAB is to provide a forum within which Consortium wide standards architecture and life cycle management issues can be discussed and deliberated with the intent of providing guidance and recommendations to the Technical Committee (TC) and the Executive Planning Committee (EPC) on these issues (OGC 06-030r12). 

During the OAB's review of a Standard, it is the responsibility of the SWG to seek a decision from the OAB on the granularity of the building block.

Scope: The decision of the OAB with regard to building block registration is limited to:

* the level of granularity of building block
* the reusability of a building block
* interfacing of a building block with others

Trigger: SWG submits a candiate Standard or a previously approved Standard for OAB review.

Inputs: 

* candidate Standard or a previously approved Standard

Process:

. OAB Chair begins a period of review by the OAB
. OAB Members propose options for an appropriate level of granularity
. OAB Chair conducts a vote on on the preferred level of granularity of the building blocks to be registered
. OAB Chair creates a ticket, on the OGC-NA Git repository, with a direction from the OAB on the level of granularity of the building block to be registered

Outputs:

* Direction from the OAB on the granularity of the building block
* Alternatively, the OAB may direct that a building block not be registered

=== Review by the OGC Naming Authority SubCommittee

The mission of the OGC Naming Authority (OGC-NA) is to provide the means through which OGC resources such as OGC documents, namespaces and ontologies can be controlled and managed such that they can provide clear and well-defined names and definitions (OGC 09-046r6).

Scope: The decision of the OGC-NA with regard to building block registration is limited to:

* the description of a building block
* the identification of a building block

Trigger: SWG submits a TC-approved Standard for registration as building blocks.

Inputs: 

* Decision of the OAB on the granularity of the building block

Process:

. OGC-NA Chair begins a period of review by the OGC-NA
. OGC-NA Chair conducts a vote on registration of the building block or as a group of building blocks
. If the vote passes, OGC Staff register the building block or group of building blocks in the register.
. If the vote fails to pass, then OGC-NA Chair asks the SWG to revise the proposal before resubmission.

Outputs:

* Registered Building Block displayed on the registry


=== Appeals

A SWG may appeal to the TC Chair if it disagrees with the decisions of the OAB or OGC-NA regarding building block registration. 

Trigger: A SWG disagrees with a decision of the OAB or OGC-NA.

Inputs:

* An Appeal Request Form

Process:

. SWG submits appeal form to the TC Chair
. TC Chair convenes an Appeals Panel consisting of OAB and OGC-NA members, and invites the SWG
. The Appeals Panel votes on whether to uphold the OAB/OGC-NA decision

Outputs:

* Final decision of the OAB

The Appeal Request Form shall contain at a minimum:

* identification of the source of the appeal (i.e. the SWG and the point of contact),
* a detailed and specific description of the situation, 
* a justification for the appeal, and
* a statement of the impact if the appeal is not successful

