[[processes]]
== Processes

=== Review by the OGC Architecture Board

Each OGC candidate Standard goes through a series of stages on the way to approval by the TC. One of those stages is the review by the OGC Architecture Board (OAB).

The mission of the OAB is to provide a forum within which Consortium wide standards architecture and life cycle management issues can be discussed and deliberated with the intent of providing guidance and recommendations to the Technical Committee (TC) and the Executive Planning Committee (EPC) on these issues (OGC 06-030r12). 

During the OAB's review of a Standard, it is the responsibility of the SWG to seek approval from the OAB on the granularity, reusability, and interfacing of the building block.

Scope: The decision of the OAB with regard to building block registration is limited to:

* approval or rejection of the proposed level of granularity of building block
* approval or rejection of the reusability of a building block
* approval or rejection of the proposed interfacing of a building block with others

Trigger: 

* SWG submits a candiate Standard or a previously approved Standard for OAB review.

Inputs: 

* Candidate Standard or a previously approved Standard
* A completed form describing the level of granularity, reusability, and interfacing of the building block

Process:

. OAB Chair begins a period of review by the OAB
. OAB evaludates the structure of the proposed building block(s)
. OAB Chair conducts a vote on the approval of the proposed level of granularity, reusability, and interfacing of the building block(s)
. OAB Chair creates a ticket, on the OGC-NA Git repository, with the result of the OAB vote

Outputs:

* OAB approval or rejection of the proposal from the SWG
* Alternatively, the OAB may direct that a building block not be registered

NOTE: OAB approval may be unconditional or conditional upon changes being made to the proposed building block.

=== Review by the OGC Naming Authority SubCommittee

The mission of the OGC Naming Authority (OGC-NA) is to provide the means through which OGC resources such as OGC documents, namespaces and ontologies can be controlled and managed such that they can provide clear and well-defined names and definitions (OGC 09-046r6).

Scope: The decision of the OGC-NA with regard to building block registration is limited to:

* the description of a building block
* the identification of a building block

Trigger: 

* OAB Chair creates a ticket, on the OGC-NA Git repository, with the result of the OAB vote

Inputs: 

* Approval by the OAB of the granularity, reusability and interfacing of the building block

Process:

. OGC-NA Chair begins a period of review by the OGC-NA
. OGC-NA Chair conducts a vote on registration of the building block or as a group of building blocks
. If the vote passes, OGC Staff register the building block or group of building blocks in the register.
. If the vote fails to pass, then OGC-NA Chair asks the SWG to revise the proposal before resubmission.

Outputs:

* Registered Building Block displayed on the registry


=== Appeals

A SWG may appeal to the TC Chair if it disagrees with the decisions of the OAB or OGC-NA regarding building block registration. 

Trigger: 

* A SWG disagrees with a decision of the OAB or OGC-NA.

Inputs:

* An Appeal Request Form

Process:

. SWG submits appeal form to the TC Chair
. TC Chair convenes an Appeals Panel consisting of OAB and OGC-NA members, and invites the SWG
. The Appeals Panel votes on whether to uphold the OAB/OGC-NA decision

Outputs:

* Final decision of the OAB

The Appeal Request Form shall contain at a minimum:

* identification of the source of the appeal (i.e. the SWG and the point of contact),
* a detailed and specific description of the situation, 
* a justification for the appeal, and
* a statement of the impact if the appeal is not successful

