== Naming Rule

This section describes the naming rule.

=== OGC name schemes

An http URI scheme [IETF RFC 3986] is defined by OGC to provide persistent names for resources of interest in geographic information infrastructures. The generic syntax for OGC names is described in [OGC Naming Authority – Procedures].

The generic syntax for OGC http URIs is

  URI = "http://www.opengis.net/" OGCResource "/" ResourceSpecificPath

The following ABNF adapted from [IETF RFC 3986] provides some basic definitions required in the rest of this document.

  segment       = *pchar
  segment-nc    = *pchar-nc
  segment-nz    = 1*pchar
  segment-nz-nc = 1*pchar-nc
  pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
  pchar-nc      = unreserved / pct-encoded / sub-delims / "@"
  pct-encoded   = "%" HEXDIG HEXDIG
  unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
  reserved      = gen-delims / sub-delims
  gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
  sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
  / "*" / "+" / "," / ";" / "="

=== Production rule for specification element names

The basic form for an OGC name that identifies an ontology resource shall be produced using the following rule:

  OGCResource = "ont"
  ResourceSpecificPath = [ aggregate "/" ] ontology [ "#" code ] = segment-nz-nc ; token denoting a set of aggregate ontologies
  ontology = segment-nz-nc ; token denoting the ontology
  code = segment-nz-nc ; localname for ontology element

The base URI (i.e. without the ‘#’ separator and ‘code’ element) is used to identify an ontology as a whole, which may import other ontologies.

A full URI denotes an ontology class or property.
