curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeClassValue.xml > ./data/Bridge.BridgeClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeConstructiveElementClassValue.xml > ./data/Bridge.BridgeConstructiveElementClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeConstructiveElementFunctionValue.xml > ./data/Bridge.BridgeConstructiveElementFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeConstructiveElementUsageValue.xml > ./data/Bridge.BridgeConstructiveElementUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeFunctionValue.xml > ./data/Bridge.BridgeFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeFurnitureClassValue.xml > ./data/Bridge.BridgeFurnitureClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeFurnitureFunctionValue.xml > ./data/Bridge.BridgeFurnitureFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeFurnitureUsageValue.xml > ./data/Bridge.BridgeFurnitureUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeInstallationClassValue.xml > ./data/Bridge.BridgeInstallationClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeInstallationFunctionValue.xml > ./data/Bridge.BridgeInstallationFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeInstallationUsageValue.xml > ./data/Bridge.BridgeInstallationUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeRoomClassValue.xml > ./data/Bridge.BridgeRoomClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeRoomFunctionValue.xml > ./data/Bridge.BridgeRoomFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeRoomUsageValue.xml > ./data/Bridge.BridgeRoomUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Bridge.BridgeUsageValue.xml > ./data/Bridge.BridgeUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingClassValue.xml > ./data/Building.BuildingClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingConstructiveElementClassValue.xml > ./data/Building.BuildingConstructiveElementClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingConstructiveElementFunctionValue.xml > ./data/Building.BuildingConstructiveElementFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingConstructiveElementUsageValue.xml > ./data/Building.BuildingConstructiveElementUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingFunctionValue.xml > ./data/Building.BuildingFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingFurnitureClassValue.xml > ./data/Building.BuildingFurnitureClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingFurnitureFunctionValue.xml > ./data/Building.BuildingFurnitureFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingFurnitureUsageValue.xml > ./data/Building.BuildingFurnitureUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingInstallationClassValue.xml > ./data/Building.BuildingInstallationClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingInstallationFunctionValue.xml > ./data/Building.BuildingInstallationFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingInstallationUsageValue.xml > ./data/Building.BuildingInstallationUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingRoomClassValue.xml > ./data/Building.BuildingRoomClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingRoomFunctionValue.xml > ./data/Building.BuildingRoomFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingRoomUsageValue.xml > ./data/Building.BuildingRoomUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingSubdivisionClassValue.xml > ./data/Building.BuildingSubdivisionClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingSubdivisionFunctionValue.xml > ./data/Building.BuildingSubdivisionFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingSubdivisionUsageValue.xml > ./data/Building.BuildingSubdivisionUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.BuildingUsageValue.xml > ./data/Building.BuildingUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.RoofTypeValue.xml > ./data/Building.RoofTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Building.RoomElevationReferenceValue.xml > ./data/Building.RoomElevationReferenceValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/CityFurniture.CityFurnitureClassValue.xml > ./data/CityFurniture.CityFurnitureClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/CityFurniture.CityFurnitureFunctionValue.xml > ./data/CityFurniture.CityFurnitureFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/CityFurniture.CityFurnitureUsageValue.xml > ./data/CityFurniture.CityFurnitureUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/CityObjectGroup.CityObjectGroupClassValue.xml > ./data/CityObjectGroup.CityObjectGroupClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/CityObjectGroup.CityObjectGroupFunctionValue.xml > ./data/CityObjectGroup.CityObjectGroupFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/CityObjectGroup.CityObjectGroupUsageValue.xml > ./data/CityObjectGroup.CityObjectGroupUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.DoorClassValue.xml > ./data/Construction.DoorClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.DoorFunctionValue.xml > ./data/Construction.DoorFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.DoorUsageValue.xml > ./data/Construction.DoorUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.ElevationReferenceValue.xml > ./data/Construction.ElevationReferenceValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.EventValue.xml > ./data/Construction.EventValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.OtherConstructionClassValue.xml > ./data/Construction.OtherConstructionClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.OtherConstructionFunctionValue.xml > ./data/Construction.OtherConstructionFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.OtherConstructionUsageValue.xml > ./data/Construction.OtherConstructionUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.WindowClassValue.xml > ./data/Construction.WindowClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.WindowFunctionValue.xml > ./data/Construction.WindowFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Construction.WindowUsageValue.xml > ./data/Construction.WindowUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.IntervalValue.xml > ./data/Core.IntervalValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.MimeTypeValue.xml > ./data/Core.MimeTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.NilReasonEnumeration.xml > ./data/Core.NilReasonEnumeration.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.OccupantTypeValue.xml > ./data/Core.OccupantTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.OtherRelationTypeValue.xml > ./data/Core.OtherRelationTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.QualifiedAreaTypeValue.xml > ./data/Core.QualifiedAreaTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.QualifiedVolumeTypeValue.xml > ./data/Core.QualifiedVolumeTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.RelationTypeValue.xml > ./data/Core.RelationTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.TemporalRelationTypeValue.xml > ./data/Core.TemporalRelationTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Core.TopologicalRelationTypeValue.xml > ./data/Core.TopologicalRelationTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Dynamizer.AuthenticationTypeValue.xml > ./data/Dynamizer.AuthenticationTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Dynamizer.SensorConnectionTypeValue.xml > ./data/Dynamizer.SensorConnectionTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Dynamizer.StandardFileTypeValue.xml > ./data/Dynamizer.StandardFileTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Dynamizer.TabulatedFileTypeValue.xml > ./data/Dynamizer.TabulatedFileTypeValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericLogicalSpaceClassValue.xml > ./data/Generics.GenericLogicalSpaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericLogicalSpaceFunctionValue.xml > ./data/Generics.GenericLogicalSpaceFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericLogicalSpaceUsageValue.xml > ./data/Generics.GenericLogicalSpaceUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericOccupiedSpaceClassValue.xml > ./data/Generics.GenericOccupiedSpaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericOccupiedSpaceFunctionValue.xml > ./data/Generics.GenericOccupiedSpaceFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericOccupiedSpaceUsageValue.xml > ./data/Generics.GenericOccupiedSpaceUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericThematicSurfaceClassValue.xml > ./data/Generics.GenericThematicSurfaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericThematicSurfaceFunctionValue.xml > ./data/Generics.GenericThematicSurfaceFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericThematicSurfaceUsageValue.xml > ./data/Generics.GenericThematicSurfaceUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericUnoccupiedSpaceClassValue.xml > ./data/Generics.GenericUnoccupiedSpaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericUnoccupiedSpaceFunctionValue.xml > ./data/Generics.GenericUnoccupiedSpaceFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Generics.GenericUnoccupiedSpaceUsageValue.xml > ./data/Generics.GenericUnoccupiedSpaceUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/LandUse.LandUseClassValue.xml > ./data/LandUse.LandUseClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/LandUse.LandUseFunctionValue.xml > ./data/LandUse.LandUseFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/LandUse.LandUseUsageValue.xml > ./data/LandUse.LandUseUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.AuxiliaryTrafficAreaClassValue.xml > ./data/Transportation.AuxiliaryTrafficAreaClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.AuxiliaryTrafficAreaFunctionValue.xml > ./data/Transportation.AuxiliaryTrafficAreaFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.AuxiliaryTrafficAreaUsageValue.xml > ./data/Transportation.AuxiliaryTrafficAreaUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.AuxiliaryTrafficSpaceClassValue.xml > ./data/Transportation.AuxiliaryTrafficSpaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.AuxiliaryTrafficSpaceFunctionValue.xml > ./data/Transportation.AuxiliaryTrafficSpaceFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.AuxiliaryTrafficSpaceUsageValue.xml > ./data/Transportation.AuxiliaryTrafficSpaceUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.ClearanceSpaceClassValue.xml > ./data/Transportation.ClearanceSpaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.HoleClassValue.xml > ./data/Transportation.HoleClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.IntersectionClassValue.xml > ./data/Transportation.IntersectionClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.MarkingClassValue.xml > ./data/Transportation.MarkingClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.RailwayClassValue.xml > ./data/Transportation.RailwayClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.RailwayFunctionValue.xml > ./data/Transportation.RailwayFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.RailwayUsageValue.xml > ./data/Transportation.RailwayUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.RoadClassValue.xml > ./data/Transportation.RoadClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.RoadFunctionValue.xml > ./data/Transportation.RoadFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.RoadUsageValue.xml > ./data/Transportation.RoadUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.SectionClassValue.xml > ./data/Transportation.SectionClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.SquareClassValue.xml > ./data/Transportation.SquareClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.SquareFunctionValue.xml > ./data/Transportation.SquareFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.SquareUsageValue.xml > ./data/Transportation.SquareUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.SurfaceMaterialValue.xml > ./data/Transportation.SurfaceMaterialValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrackClassValue.xml > ./data/Transportation.TrackClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrackFunctionValue.xml > ./data/Transportation.TrackFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrackUsageValue.xml > ./data/Transportation.TrackUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrafficAreaClassValue.xml > ./data/Transportation.TrafficAreaClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrafficAreaFunctionValue.xml > ./data/Transportation.TrafficAreaFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrafficAreaUsageValue.xml > ./data/Transportation.TrafficAreaUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrafficSpaceClassValue.xml > ./data/Transportation.TrafficSpaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrafficSpaceFunctionValue.xml > ./data/Transportation.TrafficSpaceFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.TrafficSpaceUsageValue.xml > ./data/Transportation.TrafficSpaceUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.WaterwayClassValue.xml > ./data/Transportation.WaterwayClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.WaterwayFunctionValue.xml > ./data/Transportation.WaterwayFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Transportation.WaterwayUsageValue.xml > ./data/Transportation.WaterwayUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.HollowSpaceClassValue.xml > ./data/Tunnel.HollowSpaceClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.HollowSpaceFunctionValue.xml > ./data/Tunnel.HollowSpaceFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelClassValue.xml > ./data/Tunnel.TunnelClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelConstructiveElementClassValue.xml > ./data/Tunnel.TunnelConstructiveElementClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelConstructiveElementFunctionValue.xml > ./data/Tunnel.TunnelConstructiveElementFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelConstructiveElementUsageValue.xml > ./data/Tunnel.TunnelConstructiveElementUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelFunctionValue.xml > ./data/Tunnel.TunnelFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelFurnitureClassValue.xml > ./data/Tunnel.TunnelFurnitureClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelFurnitureFunctionValue.xml > ./data/Tunnel.TunnelFurnitureFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelFurnitureUsageValue.xml > ./data/Tunnel.TunnelFurnitureUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelInstallationClassValue.xml > ./data/Tunnel.TunnelInstallationClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelInstallationFunctionValue.xml > ./data/Tunnel.TunnelInstallationFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelInstallationUsageValue.xml > ./data/Tunnel.TunnelInstallationUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.TunnelUsageValue.xml > ./data/Tunnel.TunnelUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Tunnel.hollowSpaceUsageValue.xml > ./data/Tunnel.hollowSpaceUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Vegetation.PlantCoverClassValue.xml > ./data/Vegetation.PlantCoverClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Vegetation.PlantCoverFunctionValue.xml > ./data/Vegetation.PlantCoverFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Vegetation.PlantCoverUsageValue.xml > ./data/Vegetation.PlantCoverUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Vegetation.SolitaryVegetationObjectClassValue.xml > ./data/Vegetation.SolitaryVegetationObjectClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Vegetation.SolitaryVegetationObjectFunctionValue.xml > ./data/Vegetation.SolitaryVegetationObjectFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Vegetation.SolitaryVegetationObjectUsageValue.xml > ./data/Vegetation.SolitaryVegetationObjectUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/Vegetation.SpeciesValue.xml > ./data/Vegetation.SpeciesValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/WaterBody.WaterBodyClassValue.xml > ./data/WaterBody.WaterBodyClassValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/WaterBody.WaterBodyFunctionValue.xml > ./data/WaterBody.WaterBodyFunctionValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/WaterBody.WaterBodyUsageValue.xml > ./data/WaterBody.WaterBodyUsageValue.xml
curl https://data.ogc.org/citygml-swg/CodeList_Examples_3.0.0/WaterBody.WaterLevelValue.xml > ./data/WaterBody.WaterLevelValue.xml