== Name assignment policy

=== Document types

The registers of document types http://www.opengis.net/def/doc-type is controlled by the OGC-NA. Changes to this register (additions, deletions, and supersession) shall be proposed by a submission to the OGC Naming Authority GitHub repository https://github.com/opengeospatial/NamingAuthority/issues .

=== Document element types

The registers of document element types is controlled by the OGC-NA. Changes to this register (additions, deletions, and supersession) shall be proposed by submission to the OGC Naming Authority GitHub repository https://github.com/opengeospatial/NamingAuthority/issues .

The current state of the register of document element types is shown at http://www.opengis.net/def/doc-element .

=== Names

The register of names http://www.opengis.net/def/ is controlled by the OGC-NA. Changes to this register (additions, deletions, and supersession) shall be initiated by submission to the OGC Naming Authority GitHub repository https://github.com/opengeospatial/NamingAuthority/issues .

NOTE: The approval of any new public document by OGC shall automatically trigger a registration request to OGC-NA. The name assigned shall be included on the cover page of the document.