== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

Cool URIs for the Semantic Web, W3C Interest Group Note, http://www.w3.org/TR/cooluris/ (2008)

IETF: RFC 2141 URN Syntax, http://tools.ietf.org/html/rfc2141 (1997)

IETF: RFC 2616 Hypertext Transfer Protocol -- HTTP/1.1 (1999) http://tools.ietf.org/html/rfc2616

IETF: RFC 3986 Uniform Resource Identifier (URI): Generic Syntax,  http://tools.ietf.org/html/rfc3986 (2005)

IETF: RFC 4395 Guidelines and Registration Procedures for New URI Schemes,  http://tools.ietf.org/html/rfc4395 (2006)

IETF: RFC 5141 A Uniform Resource Name (URN) Namespace for the International Organization for Standardization (ISO), http://tools.ietf.org/html/rfc5141 (2008)

IETF: RFC 5165 A Uniform Resource Name (URN) Namespace for the Open Geospatial Consortium (OGC),  http://tools.ietf.org/html/rfc5165 (2008)

IETF: RFC 5234 Augmented BNF for Syntax Specifications: ABNF, http://tools.ietf.org/html/rfc5234 (2008)

ISO: ISO 19135-1:2015 Geographic information—Procedures for item registration (2015)
