== OGC URN Resolver

RFC 5165 indicates that a resolver will be provided at http://urn.opengis.net/ . All OGC URN assignments whose status is "valid" shall be visible through the resolver.

There are two alternative rules for making an http URI (URL) from the name in order to request the resource:

{counter:item_number:1}. Create an equivalent http URI as follows:

.. replace the initial "ogc:urn:" with "http://www.opengis.net/"
.. replace any occurrence of "::" with "/0/"
.. replace all other occurrences of ":" with "/".

e.g. urn:ogc:doc:DP:WaterML:1.0 -> http://www.opengis.net/doc/DP/WaterML/1.0

{counter:item_number:2}. Use the URN as a parameter to a resolver request:
e.g. http://urn.opengis.net?id=urn:ogc:doc:DP:WaterML:1.0

*NOTE:* the first approach is similar to the rule given in clause 2.8 of the ISO URN NID specification (IETF RFC 5141).

*NOTE:* the first approach should be consistent with the http URI name variants described in this document and in OGC Name Type Specifications.

An http GET request with either of these URLs should result in a locator for the named resource with http response 307 or 303 [IETF RFC 2616]. 303 shall indicate a 'non-information resource' [Cool URIs for the Semantic Web], and 307 otherwise.
