== Historical note on URNs and URLs (informative)

URNs have been used for some years by OGC for the persistent identification of resources governed by OGC, and also for some resources governed externally for which there were not persistent URIs available (especially EPSG definitions).

At the time that OGC started using URNs, it appeared to be a good option for persistent identification, avoiding some undesirable effects and expectations around URLs. In particular, URN NID registrations (governed by IETF through IANA) are forever, while http domain registration is only as long as the owner remembers, and furthermore http server maintenance is a skilled job. There was also a general principle at stake: identification and location are different functions.

In the meantime, however, the rest of the web world has moved on. The current version of the URL story is that

- a URL is a 'http URI' (often, though incorrectly, abbreviated to just URI), which is first and foremost a (potentially persistent) identifier

- http URI has the highly desirable characteristic that the already deployed DNS system and http protocol mean that no independent resolver is required

The latter overcomes a legitimate criticism of all non-http URI schemes. However, use of http URIs as persistent identifiers requires a reliable strategy for managing the domain, the server, and in particular to insulate the identifier scheme from organizational name-changes that may ripple through to domain names (e.g. opengis.net → opengeospatial.org).

In this context, the existing procedures for URN assignment, accompanied by well controlled registers for elements within these, puts OGC in a good position for a transition. The name production rules in this document are almost transparent to the use of http URIs in place of URNs.

Some interesting (at times somewhat polemical) discussion of the merits of http URIs and folly of all other flavors is found in Berners-Lee's 'Cool URIs don't change'

<http://www.w3.org/Provider/Style/URI>, and Thompson and Orchard's 'URNs, Namespaces and Registries' <http://www.w3.org/2001/tag/doc/URNsAndRegistries-50>. Booth's 'The URI Lifecycle ...' <http://dbooth.org/2009/lifecycle/> reinforces the story that persistence is about governance and not protocol.
