== Examples

=== Specification

Example 1: A specification

  http://www.opengis.net/spec/OMXML/2.0

NOTE: The specification as a whole has a single version designator. Elements within the specification cannot be versioned independently from the specification as a whole.

=== Requirements class

Example 2: A requirements class within the previous specification

http://www.opengis.net/spec/OMXML/2.0/req/measurement

NOTE: The first step after the /req/ field provides the name of a requirements-class.

=== Specification requirement

Example 3: A specification requirement, within the previous requirements class:

  http://www.opengis.net/spec/OMXML/2.0/req/measurement/result-measure

NOTE: The second step after the /req/ field provides the name of a requirements-module or requirement.

=== Conformance class

Example 4: A conformance class within the previous specification

  http://www.opengis.net/spec/OMXML/2.0/conf/measurement

NOTE: The first step after the /conf/ field provides the name of a conformance-class.

=== Conformance test

Example 5: A conformance test within the previous conformance-class

  http://www.opengis.net/spec/OMXML/2.0/conf/measurement/result-measure

NOTE: The second step after the /conf/ field provides the name of a conformance-module or conformance-test.

=== Requirements module

Example 6: A requirements module

http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/datetime

NOTE: Instead of the /req/ segment, /rm/ is used.

NOTE: This is based on the example of https://docs.ogc.org/is/20-057/20-057.html#_datetime_query_parameter_request_and_response