== Naming Rule

This section describes the naming rule.

=== OGC name schemes

URI schemes [IETF RFC 3986] are defined by OGC to provide persistent names for resources of interest in geographic information infrastructures. The generic syntax for OGC names is described in [OGC Naming Authority – Procedures].

The generic syntax for OGC http URIs is

  URI = "http://www.opengis.net/" OGCResource "/" ResourceSpecificPath

The following ABNF adapted from [IETF RFC 3986] provides some basic definitions required in the rest of this document.

  segment       = *pchar
  segment-nc    = *pchar-nc
  segment-nz    = 1*pchar
  segment-nz-nc = 1*pchar-nc
  pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
  pchar-nc      = unreserved / pct-encoded / sub-delims / "@"
  pct-encoded   = "%" HEXDIG HEXDIG
  unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
  reserved      = gen-delims / sub-delims
  gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
  sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                / "*" / "+" / "," / ";" / "="

=== Production rule for specification element names

An OGC name for a normative specification element shall be produced using the following rule:

  OGCResource          = "spec"
  ResourceSpecificPath = standard "/" version [ "/" class "/" name *("/" name) ]
  standard             = segment-nz-nc ; value registered as a doc-name for an OGC standard according to [OGC-NA Name type specification – documents]
  version              = 1*DIGIT "." 1*DIGIT ["." 1*DIGIT] ; value registered as a doc-version for an OGC implementation standard according to [OGC-NA Name type specification – documents]
  class                = "req" / "conf"  / "rm"
  name                 = segment-nz-nc


=== Segments as Resources

This policy considers each segment along the path of a specification element URI as a resource. Therefore, descriptive information about the resource at that segment shall be returned when the resource is accessed as specified below:

[loweralpha]
. The URI `\http://www.opengis.net/spec` shall return information describing this URI as the namespace for specification elements.
. The URI `\http://www.opengis.net/spec/<standard>` shall return information describing this URI as the namespace for specification elements of the standard named by the `<standard>` segment.
. The URI `\http://www.opengis.net/spec/<standard>/<version>` shall return information describing this URI as the namespace for specification elements of version `<version>` of standard `<standard>`.
. The URI `\http://www.opengis.net/spec/<standard>/<version>/req` shall return information describing this URI as the namespace for requirements and requirements classes in version `<version>` of standard `<standard>`.
. The URI `\http://www.opengis.net/spec/<standard>/<version>/rm` shall return information describing this URI as the namespace for requirements modules in version `<version>` of standard `<standard>`.
. The URI `\http://www.opengis.net/spec/<standard>/<version>/conf` shall return information describing this URI as the namespace for conformance classes and conformance tests in version `<version>` of standard `<standard>`.

=== Explanation

This policy document provides a URI structure for specification components, as required by Req 2 in the OGC Policy document [OGC Specification Model – Modular Specifications]:

_Req 2 Each component of the standard, including requirements, requirements modules, requirements classes, conformance test cases, conformance modules and conformance classes shall be assigned a URI as specified by the OGC naming authority or its equivalent._

The policy also includes the following requirement relevant to the naming scheme design:

_Req 14 For the sake of consistency and readability, all requirements classes and all conformance test classes shall be explicitly named, with corresponding requirements classes and conformance test classes having similar names._

The consistency constraint described in Req 14 links the names of conformance classes to requirements classes. This is not formalized in the production rules, but will be checked during the registration process.

Names for Requirements Classes or Conformance Classes are constructed by appending fields to the name for the Specification. Names for Modules, Requirements and Tests are constructed by appending additional fields to the names for the Requirements Class or Conformance Class. In this way the names reflect the fact that each Module, Requirement and Test is owned by a single Requirements Class or Conformance Class, and each Requirements Class or Conformance Class is owned by a single Specification as specified in the https://www.ogc.org/standards/modularspec[OGC Specification Model – Modular Specifications (OGC 08-131r3)].
