== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, terms from *The Specification Model — A Standard for Modular specifications* (OGC 08-131r3) apply. The following terms and definitions are reproduced below for the reader's convenience:

=== *requirement*
expression in the content of a document conveying criteria to be fulfilled if compliance with the document is to be claimed and from which no deviation is permitted

(Source: ISO Directives Part 2)

=== *requirements module*

aggregate of requirements and recommendations of a specification against a single standardization target type

(Source: OGC 08-131r3)

=== *requirements class*
aggregate of all requirement modules that must all be satisfied to satisfy a conformance test class

(Source: OGC 08-131r3)

=== *conformance test class*
set of conformance test modules that must be applied to receive a single certificate of conformance

NOTE: When no ambiguity is possible, the word 'test' may be left out, so *conformance test class* maybe called a *conformance class*.

(Source: OGC 08-131r3)

