=== digital rights management

packaging, distributing, controlling, and tracking content based on rights and licensing information

NOTE: DRM covers a much broader spectrum of capabilities and underlying technologies supporting description, identification, trading, protecting, monitoring, and tracking of all forms of rights usages for both tangible and intangible (electronic) assets, including the management of rights-holders relationships. See, for example, Reference [5][of ISO 19153:2014 - Iannella R. Digital Rights Management (DRM) Architectures. D-Lib. 2001 June, 7 (6) Available
at: http://www.dlib.org/dlib/june01/iannella/06iannella.html]. “Digital” refers to the material over which the rights exist. “Rights” applies to the Intellectual Property rights linked to the material. “Management” covers both the defining of policy and enforcing that policy in such a way that rights are respected. The ultimate goal of a distributed DRM system is for content authors to be able to project policies governing their content into remote environments with confidence that those policies will be respected by the remote nodes. For the purposes of this International Standard, DRM is taken to mean technology that enables the secure distribution (and where appropriate, sale) of digital media content on the Internet.

(Source: ISO 19153:2014)

