=== general public licence

licence containing rights accorded to the general public without an existing agreement

NOTE: GPLs can be granted by the owner of a resource or can be applied to a resource by law, usually as part of the copyright law. The most obvious GPL concept is fair use in the United States for copyrighted material. Other GPL rights can be demanded by the source of the resource or other “public good” considerations.

NOTE: The most widespread use of GPL is in reference to the GNU GPL, which is commonly abbreviated simply as GPL when it is understood that the term refers to the GNU GPL. One of the basic tenets of the GPL is that anyone who acquires the material shall make it available to anyone else under the same licensing agreement. The GPL does not cover activities other than the copying, distributing, and modifying of the source code. A GPL is also referred to as a copyleft, in contrast to a copyright, which identifies the proprietary rights of material.

(Source: ISO 19153:2014)

