=== basic administrative unit

administrative entity, subject to registration (by law), or recordation [by informal right , or customary right, or another social tenure relationship], consisting of zero or more spatial units against which (one or more) unique and homogeneous rights [e.g. ownership right or land  use right], responsibilities or restrictions are associated to the whole entity, as included in a land administration system

NOTE: 'Unique' means that a right, restriction, or responsibility is held by one or more parties (e.g. owners or users) for the whole basic administrative unit. 'Homogeneous' means that a right, restriction or responsibility (e.g. ownership, use, social tenure, lease, or easement) affects the whole basic administrative unit. For a restriction, zero parties are a possibility.

NOTE: A basic administrative unit may play the role of party, e.g. when the right holder is a basic administrative unit (and not a person or organization).

NOTE: A baunit should get a unique identifier when registered, or recorded.

NOTE: A baunit can consist of zero spatial units, when a registry exists, and not a cadastre.

NOTE: Restrictions and responsibilities can be associated with their own baunits, each with their own type of spatial unit.

(Source: ISO 19152:2012)

