=== address

structured information that allows the unambiguous determination of an object for purposes of identification and location

NOTE: The object is identifiable in the real world, i.e. electronic and virtual addresses are excluded.

NOTE: “Identification” refers to the fact that the structured information in the address unambiguously determines the object, i.e. it helps the human to identify the object. In other words, “identification” here does not refer to unique identifiers in a database or dataset.

NOTE: There can be many addresses for an object, but at any moment (or lifecycle stage), an address unambiguously determines a single object (see ISO 19160-1:2015, Annex D for examples).

NOTE: Two addresses from two different address classes (i.e. they have different sets of components) for the same addressable object are two different addresses (refer to ISO 19160-1:2015, Annex E for more examples).

NOTE: Two addresses for the same addressable object and from the same address class, but in two different languages are two different addresses (refer to ISO 19160-1:2015, Annex E for more examples).

NOTE: In addition to the addressable object, there may be a multitude of people, organizations, addressees or other objects associated with an address. These are external to the address model (refer to ISO 19160-1:2015, Annex C and Annex F for examples).

(Source: ISO 19160-1:2015)

