=== normal section curve <differential geometry, geodesy>

plane curve segment containing the normal at one of its terminal points

NOTE: The usual construction begins by choosing one of the end points, the normal to the surface at that end point, and the location of the other end point and creating a plane in <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo linebreak="newline"/>    <mi>m</mi>    <mi>a</mi>    <mi>t</mi>    <mi>h</mi>    <mi>b</mi>    <mi>b</mi>    <msup>      <mi>E</mi>      <mn>3</mn>    </msup>  </mstyle></math>, which is then intersected with the datum. This curve is a normal section curve between these two points, containing the normal to the surface at the first point. On the sphere, this is the geodesic, and the two normal section curves are equal. On an ellipsoidal datum, the same is true for two points on the equator, or two points on the same meridian plane, but false in general. The reason is that in these cases the plane through the two points and the centre of the ellipsoid are planes of symmetry for the ellipsoid dividing the ellipsoid into symmetric "mirror" image halves. In general, the geodesic between the two points lies between the two normal section curves.

(Source: ISO 19107:2019)

