=== transfer node

location that facilitates transfers between transport modes, transport networks and/or transport means

NOTE: A transfer node may contain other transfer nodes and may be related to one or more transport modes and transport networks. It may also contain stop points and facilities for the users of the transfer node. A transfer node may host services that are provided to the users of the transfer node, e.g. information services, ticket sales, etc.

NOTE: A transfer node may be a part of a hierarchy of transfer nodes. Thus, a transfer node may be related to many transport modes and transport networks. However, only transfer nodes that are related to just one transport network will have stop points.

NOTE: The stop points related to different transfer nodes, which may serve different transport modes and networks, may, in real life, have the same physical locations. A tram and a bus may for example share the same platform, but conceptually they may belong to different transfer nodes.

(Source: ISO 19147:2015)

