=== addressee

party who is the ultimate recipient of a delivery item or service

NOTE: The addressee may be explicitly defined as part of the postal address, or may be implicit. For example, in certain countries, omission of addressee information is taken as implying that delivery is to be to an individual or legal entity having legal access to the delivery point.

NOTE: Mr. or Mrs. Smith specifies that the addressee is either of two individuals, while Mr. Jones and Mrs. Smith denote that the addressee is a group of two individuals. See also role descriptor.

NOTE: The use made by the postal operator of addressee and mailee data might be dependent on the postal service applicable to the postal item. For some services, such as registered mail, the postal operator’s responsibility might include ensuring that the addressee or a duly authorized representative acknowledges receipt of the postal item. In other cases, addressee data could be purely informative or used by the postal operator only for consistency checking and/or for the activation of forwarding services. In other cases, it might be used for sorting or sequencing purposes prior to delivery, e.g. in the case of business mail being pre-sequenced by department or individual company official.

NOTE: In some countries, the addressee may be an abstraction such as “postal customer”.

(Source: ISO 19160-4:2023)

(Source: ISO 19160-4:2017)

