=== connected

property of a topological space implying that only the entire space or the empty set are the only subsets which are both open and closed

NOTE: The formal definition of connected is that any pair of locally open sets whose union is the entire space must have a non-empty intersection. <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo linebreak="newline"/>    <mi>t</mi>    <mi>e</mi>    <mi>x</mi>    <mi>t</mi>    <mrow>      <mi>a</mi>      <mi>t</mi>      <mi>o</mi>      <mi>p</mi>      <mi>o</mi>      <mi>l</mi>      <mi>o</mi>      <mi>g</mi>      <mi>i</mi>      <mi>c</mi>      <mi>a</mi>      <mi>l</mi>      <mi>s</mi>      <mi>p</mi>      <mi>a</mi>      <mi>c</mi>      <mi>e</mi>    </mrow>    <mi>T</mi>    <mo linebreak="newline"/>    <mi>t</mi>    <mi>e</mi>    <mi>x</mi>    <mi>t</mi>    <mrow>      <mi>i</mi>      <mi>s</mi>      <mi>c</mi>      <mi>o</mi>      <mi>n</mi>      <mi>n</mi>      <mi>e</mi>      <mi>c</mi>      <mi>t</mi>      <mi>e</mi>      <mi>d</mi>      <mi>i</mi>      <mi>f</mi>      <mi>a</mi>      <mi>n</mi>      <mi>d</mi>      <mi>o</mi>      <mi>n</mi>      <mi>l</mi>      <mi>y</mi>      <mi>i</mi>      <mi>f</mi>    </mrow>    <mrow>      <mo>[</mo>      <mo linebreak="newline"/>      <mi>f</mi>      <mi>o</mi>      <mi>r</mi>      <mi>a</mi>      <mi>l</mi>      <mi>l</mi>      <mi>X</mi>      <mo>,</mo>      <mi>Y</mi>      <mo linebreak="newline"/>      <mi>s</mi>      <mi>u</mi>      <mi>b</mi>      <mi>s</mi>      <mi>e</mi>      <mi>t</mi>      <mi>T</mi>      <mo linebreak="newline"/>      <mi>b</mi>      <mi>a</mi>      <mi>c</mi>      <mi>k</mi>      <mi>e</mi>      <mi>p</mi>      <mi>s</mi>      <mi>i</mi>      <mi>l</mi>      <mi>o</mi>      <mi>n</mi>      <mi>X</mi>      <mo linebreak="newline"/>      <mi>c</mi>      <mi>u</mi>      <mi>p</mi>      <mi>Y</mi>      <mo>=</mo>      <mi>T</mi>      <mo>]</mo>    </mrow>    <mo linebreak="newline"/>    <mi>i</mi>    <mi>m</mi>    <mi>p</mi>    <mi>l</mi>    <mi>i</mi>    <mi>e</mi>    <mi>s</mi>    <mrow>      <mo>[</mo>      <mi>X</mi>      <mo linebreak="newline"/>      <mi>c</mi>      <mi>a</mi>      <mi>p</mi>      <mi>Y</mi>      <mo linebreak="newline"/>      <mi>n</mi>      <mi>e</mi>      <mo linebreak="newline"/>      <mi>e</mi>      <mi>m</mi>      <mi>p</mi>      <mi>t</mi>      <mi>y</mi>      <mi>s</mi>      <mi>e</mi>      <mi>t</mi>      <mo>]</mo>    </mrow>  </mstyle></math> This formal definition is difficult to use. The term path connected, defined below is equivalent for the purposed of this document. The use or "finite precision" coordinates makes sets which are connected but not path connected impossible to represent. In all cases "connected" is used, but "path connected" is easier to test and to visualize.

(Source: ISO 19107:2019)

