=== empty set <mathematics>

set without any elements

NOTE: Sets are equal if they contain exactly the same elements. Since any two empty sets would share exactly the same contained elements (by definition none), they are, by definition, equal. The empty set (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math>) can be considered a geometric entity, because all the elements it contains are points. This is a vacuous statement since the set <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math> contains no elements, and therefore the "for all" statement has nothing to test and is thus true in each of its non-existent cases. There are a lot of true but vacuous statements in proofs about <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math>. This confuses some programmers since many systems use type safe sets, in which the class of the entities determines a class for the container set. The math does not care about "class" and only sees sets; so that an empty set of aardvarks and an empty set of zebras in mathematics are (is?) the same set. The other confusion is that <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math> is not the database Null introduced by Codd and used in relational and other query languages in 3 valued logic. Null means unknown and many statements involving Null are undecidable (neither provably true nor provably false). The empty set is not "lack of knowledge" but certainty in the nonexistence of elements in the set. Most statements beginning "for all elements in <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math>" are true, but vacuous. Most statements beginning "there exist an element in <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math>" are always categorically false. It is almost impossible to construct an undecidable statement about <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math>. Null and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x2205;</mi>  </mstyle></math> are not related. "Void" can mean "invalid" or "completely empty."

(Source: ISO 19107:2019)

