=== bearing

horizontal angle, tangent or direction at a point

NOTE: This definition (as opposed to the one in ISO 19162:2015) is required for this document  because the concept is used in other definitions, such as first geodetic problem and second geodetic problem. The two definitions are nearly equivalent because the tangent of a curve on a surface is a tangent to the surface and does specify a direction. Usual 2D measure of bearing can be an angle equivalently measured from North clockwise, or a unit tangent vector. If the coordinate system is spatially 3D, the horizontal bearing angle may also need to a vertical altitude angle to be complete. If a reference curve (as used in ISO 19162) is parameterized by arc length, then the "derivative" is a unit vector. If another parameterization <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>t</mi>  </mstyle></math> is used, then the derivative should be normalized (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mfrac>      <mover>        <mi>&#x3c4;</mi>        <mo>&#x2192;</mo>      </mover>      <mrow>        <mo>&#x2225;</mo>        <mover>          <mi>&#x3c4;</mi>          <mo>&#x2192;</mo>        </mover>        <mo>&#x2225;</mo>      </mrow>    </mfrac>    <mo>&#x3b;</mo>    <mover>      <mi>c</mi>      <mo>.</mo>    </mover>    <mrow>      <mo>(</mo>      <mi>t</mi>      <mo>)</mo>    </mrow>    <mo>=</mo>    <mover>      <mi>&#x3c4;</mi>      <mo>&#x2192;</mo>    </mover>    <mo>&#x3b;</mo>  </mstyle></math>). This is useful, since parameterization by arc length can be computationally difficult. The numeric representation of a vector depends on the coordinate system. The bearing is not dependent on a coordinate system, but it can be represented in any reasonable system. The bearing is not dependent on its various representations.

(Source: ISO 19107:2019)

