=== ellipsoid <geodesy>

geometric reference surface embedded in 3D Euclidean space represented by an ellipsoid of revolution where the rotation is about the polar axis

NOTE: For the Earth the rotation is about the polar axis. This results in an oblate ellipsoid with midpoint of the foci located at the nominal centre of the Earth.

NOTE: The two usual algorithms for latitude on an ellipsoid and on a sphere (such as used in spherical coordinates) are only equivalent if the ellipsoid is a sphere, having all radii equal in all directions. The problem is that a radial line from the centre of a general ellipsoid does not always cross the surface of the ellipsoid orthogonally. In general, planar slices through the centre do not intersect the surface orthogonally, and therefore the curves that correspond to the great circles of a sphere are not geodesics on the ellipsoid.

NOTE: The topology of the ellipsoid is inherited from the 𝔼3 space in which it is embedded. The difference is that metrics such as distance and direction on the ellipsoid are restricted to curves wholly on the surface and vectors tangent to the surface.at

(Source: ISO 19107:2019)

