=== product level <earth observation>

number indicating the degree of processing that has been performed on the observed data

NOTE: Product levels 0 through 4 indicate the degree of processing performed on the raw data to convert them into more useful parameters and formats. The Committee on Earth Observation Satellites (CEOS) defines product levels as follows: - Raw Data: Data in their original packets, as received from a satellite. - Level 0: Reconstructed unprocessed instrument data at full space time resolution with all available supplemental information to be used in subsequent processing (e.g. ephemeris, health and safety) appended. - Level 1: Unpacked, reformatted level 0 data, with all supplemental information to be used in subsequent processing appended. Optional radiometric and geometric correction applied to produce parameters in physical units. Data generally presented as full - Level 2: Retrieved environmental variables (e.g. ocean wave height, soil moisture, ice concentration) at the same resolution and location as the level 1 source data. - Level 3: Data or retrieved environmental variables which have been spatially and/or temporally re-sampled (i.e. derived from level 1 or 2 products). Such re-sampling may include averaging and compositing. - Level 4: Model output or results from analyses of lower level data (i.e. variables that are not directly measured by the instruments but are derived from these measurements).

NOTE: The product levels defined here are derived from satellite remote sensing heritage. For the case of airborne and in situ observations, these do not necessarily apply, but may be used as appropriate for indicating the degree of processing performed on the observed data.

NOTE: Adapted from Reference [9].

(Source: ISO 19165-2:2020)

