=== barycentric coordinates <coordinate geometry>

point in a <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>n</mi>  </mstyle></math>-dimension coordinate system using <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>n</mi>    <mo>+</mo>    <mn>1</mn>  </mstyle></math> numbers, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mrow>      <mo>(</mo>      <mrow>        <mo>[</mo>        <msub>          <mi>u</mi>          <mn>0</mn>        </msub>        <mo>,</mo>        <msub>          <mi>u</mi>          <mn>1</mn>        </msub>        <mo>,</mo>        <msub>          <mi>u</mi>          <mn>2</mn>        </msub>        <mo>,</mo>        <msub>          <mi>u</mi>          <mn>3</mn>        </msub>        <mo>,</mo>        <mo>&#x2e;</mo>        <mo>&#x2e;</mo>        <mo>&#x2e;</mo>        <mo>,</mo>        <msub>          <mi>u</mi>          <mi>n</mi>        </msub>        <mo>]</mo>      </mrow>      <mo linebreak="newline"/>      <mi>b</mi>      <mi>a</mi>      <mi>c</mi>      <mi>k</mi>      <mi>e</mi>      <mi>p</mi>      <mi>s</mi>      <mi>i</mi>      <mi>l</mi>      <mi>o</mi>      <mi>n</mi>      <mrow>        <mo>[</mo>        <mrow>          <mo>[</mo>          <mn>0</mn>          <mo linebreak="newline"/>          <mi>l</mi>          <mi>e</mi>          <mi>q</mi>          <msub>            <mi>u</mi>            <mi>i</mi>          </msub>          <mo linebreak="newline"/>          <mi>l</mi>          <mi>e</mi>          <mi>q</mi>          <mn>1</mn>          <mo>]</mo>        </mrow>        <mo linebreak="newline"/>        <mi>w</mi>        <mi>e</mi>        <mi>d</mi>        <mi>g</mi>        <mi>e</mi>        <mo linebreak="newline"/>        <mi>s</mi>        <mi>u</mi>        <mi>m</mi>        <msub>          <mi>u</mi>          <mi>i</mi>        </msub>        <mo>=</mo>        <mn>1</mn>        <mo>&#x2e;</mo>        <mn>0</mn>        <mo>]</mo>      </mrow>      <mo>)</mo>    </mrow>  </mstyle></math>, in which the location of a point of an n-simplex (of any dimension) is specified by a weighted centre of mass of equal masses placed at its vertices using vector algebra of the <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msup>      <mstyle mathvariant="double-struck">        <mi>R</mi>      </mstyle>      <mi>n</mi>    </msup>  </mstyle></math> used in the coordinate reference system

NOTE: Even though there are <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>n</mi>    <mo>+</mo>    <mn>1</mn>  </mstyle></math> coordinates in a barycentric coordinate system, the topological dimension is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>n</mi>  </mstyle></math>, since the restriction (sums to 1.0) loses 1 degree of freedom (once you have <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>n</mi>  </mstyle></math> ordinates, the remaining one is determined such as <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>u</mi>      <mi>n</mi>    </msub>    <mo>=</mo>    <mn>1.0</mn>    <mi>−</mi>    <mrow>      <munderover>        <mo>&#x2211;</mo>        <mrow>          <mi>i</mi>          <mo>=</mo>          <mn>0</mn>        </mrow>        <mrow>          <mi>n</mi>          <mo>&#x2212;</mo>          <mn>1</mn>        </mrow>      </munderover>      <msub>        <mi>u</mi>        <mi>i</mi>      </msub>    </mrow>  </mstyle></math>. he coordinates for the simplex are all non-negative, but the system can be extended outside of the simples by using negative numbers. If the ordinates are all positive, then the point is inside (interior to) the <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>n</mi>  </mstyle></math>-simplex. If one of them is 1.0 and the other 0, this is a corner of the simplex. If one of them is zero and the others still each greater than or equal to zero, the point is on the <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>n</mi>    <mo>&#x2212;</mo>    <mn>1</mn>  </mstyle></math>-simplex opposite the vertex zeroed out. If any are negative, the point is outside of the simplex. The coordinates are dependent on the underlying coordinate reference system of the source data.

(Source: ISO 19107:2019)

