=== ancillary data <earth observation>

data which are not obtained from the sensor itself (usually provided in the science telemetry) and have the primary purpose to serve the processing of instrument data

NOTE: Ancillary data refers to data that exist purely to serve the data processing. Auxiliary data, while helping the process, are also datasets in their own right.

NOTE: Ancillary data may be 'engineering', 'core housekeeping' or 'subsystem' data obtained from other parts of the measurement platform. It may include parameters such as position and velocity, attitude and its range of change, time, temperatures, pressures, internally produced magnetic fields, and other environmental measurements.

NOTE: Some missions may treat ancillary data as datasets in their own right, thus blurring the distinction being made here between ancillary and auxiliary data.

NOTE: The definition in the original source is tailored to spaceborne Earth observations. It has been slightly modified here to be more general. The concept is that ancillary data are those not collected by the sensor itself and that their primary purpose to serve processing applies to Earth observation data from airborne and in situ instruments as well.

NOTE: Adapted from Reference [8].

(Source: ISO 19165-2:2020)

