=== Stokes parameters

set of four real quantities, which completely describe the polarization state of monochromatic or quasi-monochromatic radiation

NOTE: The parameters are, collectively, known as the Stokes Real {ordered}, a <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mn>4</mn>    <mo>&#xd7;</mo>    <mn>1</mn>  </mstyle></math> Real {ordered}.

NOTE: The Stokes parameters were introduced as a mathematically convenient alternative by Sir George Stokes.[14,17] These four parameters are related to the horizontally and vertically polarized components of electric field by: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mrow>      <mo>[</mo>      <mtable>        <mtr>          <mtd>            <mi>I</mi>          </mtd>        </mtr>        <mtr>          <mtd>            <mi>Q</mi>          </mtd>        </mtr>        <mtr>          <mtd>            <mi>U</mi>          </mtd>        </mtr>        <mtr>          <mtd>            <mi>V</mi>          </mtd>        </mtr>      </mtable>      <mo>]</mo>    </mrow>    <mo>=</mo>    <mfrac>      <mn>1</mn>      <mi>&#x3b7;</mi>    </mfrac>    <mrow>      <mo>[</mo>      <mtable>        <mtr>          <mtd>            <mrow>              <mo>&#x2329;</mo>              <msup>                <mrow>                  <mo>|</mo>                  <mrow>                    <msub>                      <mi>E</mi>                      <mo></mo>                    </msub>                    <mtext>v</mtext>                  </mrow>                  <mo>|</mo>                </mrow>                <mn>2</mn>              </msup>              <mo>&#x232a;</mo>            </mrow>            <mo>+</mo>            <msup>              <mrow>                <mo>&#x2329;</mo>                <mrow>                  <mo>|</mo>                  <mrow>                    <msub>                      <mi>E</mi>                      <mo></mo>                    </msub>                    <mtext>h</mtext>                  </mrow>                  <mo>|</mo>                </mrow>                <mo>&#x232a;</mo>              </mrow>              <mn>2</mn>            </msup>          </mtd>        </mtr>        <mtr>          <mtd>            <msup>              <mrow>                <mo>&#x2329;</mo>                <mrow>                  <mo>|</mo>                  <mrow>                    <msub>                      <mi>E</mi>                      <mo></mo>                    </msub>                    <mtext>v</mtext>                  </mrow>                  <mo>|</mo>                </mrow>                <mo>&#x232a;</mo>              </mrow>              <mn>2</mn>            </msup>            <mo>&#x2212;</mo>            <msup>              <mrow>                <mo>&#x2329;</mo>                <mrow>                  <mo>|</mo>                  <mrow>                    <msub>                      <mi>E</mi>                      <mo></mo>                    </msub>                    <mtext>h</mtext>                  </mrow>                  <mo>|</mo>                </mrow>                <mo>&#x232a;</mo>              </mrow>              <mn>2</mn>            </msup>          </mtd>        </mtr>        <mtr>          <mtd>            <mn>2</mn>            <mo></mo>            <mtext>Re</mtext>            <mrow>              <mo>&#x2329;</mo>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <mtext>v</mtext>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <msup>                <mtext>h</mtext>                <mi>&#x2217;</mi>              </msup>              <mo>&#x232a;</mo>            </mrow>          </mtd>        </mtr>        <mtr>          <mtd>            <mn>2</mn>            <mo></mo>            <mtext>Im</mtext>            <mrow>              <mo>&#x2329;</mo>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <mtext>v</mtext>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <msup>                <mtext>h</mtext>                <mi>&#x2217;</mi>              </msup>              <mo>&#x232a;</mo>            </mrow>          </mtd>        </mtr>      </mtable>      <mo>]</mo>    </mrow>  </mstyle></math>

where

<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>E</mi>      <mo></mo>    </msub>    <mtext>v</mtext>  </mstyle></math> is the vertically polarized component of electric field;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>E</mi>      <mo></mo>    </msub>    <mtext>h</mtext>  </mstyle></math> is the horizontally polarized component of electric field.

The units of the Stokes parameters are <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>W</mi>    <mo>/</mo>    <msup>      <mi>m</mi>      <mn>2</mn>    </msup>  </mstyle></math>. The first Stokes parameter (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>I</mi>  </mstyle></math>) gives the total radiation power density, and the second Stokes parameter (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>Q</mi>  </mstyle></math>) represents the power density difference between the two linearly polarized components. The third and fourth Stokes parameters (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>U</mi>  </mstyle></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>V</mi>  </mstyle></math>) describe the correlation between these two components.

NOTE: For microwave remote sensing, modified Stokes parameters are often used. Under the Rayleigh-Jeans approximation, the modified Stokes parameters in brightness temperature are given by the following formula:[19], [37] <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mrow>      <mo>[</mo>      <mtable>        <mtr>          <mtd>            <msub>              <mi>T</mi>              <mo></mo>            </msub>            <mtext>v</mtext>          </mtd>        </mtr>        <mtr>          <mtd>            <msub>              <mi>T</mi>              <mo></mo>            </msub>            <mtext>h</mtext>          </mtd>        </mtr>        <mtr>          <mtd>            <msub>              <mi>T</mi>              <mn>3</mn>            </msub>          </mtd>        </mtr>        <mtr>          <mtd>            <msub>              <mi>T</mi>              <mn>4</mn>            </msub>          </mtd>        </mtr>      </mtable>      <mo>]</mo>    </mrow>    <mo>=</mo>    <mfrac>      <msup>        <mi>&#x3bb;</mi>        <mn>2</mn>      </msup>      <mrow>        <mo></mo>        <mtext>k</mtext>        <mi>&#x3b7;</mi>        <mi>B</mi>      </mrow>    </mfrac>    <mrow>      <mo>[</mo>      <mtable>        <mtr>          <mtd>            <mrow>              <mo>&#x2329;</mo>              <msup>                <mrow>                  <mo>|</mo>                  <mrow>                    <msub>                      <mi>E</mi>                      <mo></mo>                    </msub>                    <mtext>v</mtext>                  </mrow>                  <mo>|</mo>                </mrow>                <mn>2</mn>              </msup>              <mo>&#x232a;</mo>            </mrow>          </mtd>        </mtr>        <mtr>          <mtd>            <mrow>              <mo>&#x2329;</mo>              <msup>                <mrow>                  <mo>|</mo>                  <mrow>                    <msub>                      <mi>E</mi>                      <mo></mo>                    </msub>                    <mtext>h</mtext>                  </mrow>                  <mo>|</mo>                </mrow>                <mn>2</mn>              </msup>              <mo>&#x232a;</mo>            </mrow>          </mtd>        </mtr>        <mtr>          <mtd>            <mn>2</mn>            <mo></mo>            <mtext>Re</mtext>            <mrow>              <mo>&#x2329;</mo>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <mtext>v</mtext>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <msup>                <mtext>h</mtext>                <mi>&#x2217;</mi>              </msup>              <mo>&#x232a;</mo>            </mrow>          </mtd>        </mtr>        <mtr>          <mtd>            <mn>2</mn>            <mo></mo>            <mtext>Im</mtext>            <mrow>              <mo>&#x2329;</mo>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <mtext>v</mtext>              <msub>                <mi>E</mi>                <mo></mo>              </msub>              <msup>                <mtext>h</mtext>                <mi>&#x2217;</mi>              </msup>              <mo>&#x232a;</mo>            </mrow>          </mtd>        </mtr>      </mtable>      <mo>]</mo>    </mrow>  </mstyle></math> 
where <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mo></mo>    </msub>    <mtext>v</mtext>  </mstyle></math>, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mo></mo>    </msub>    <mtext>h</mtext>  </mstyle></math>, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mn>3</mn>    </msub>  </mstyle></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mn>4</mn>    </msub>  </mstyle></math> are, respectively, the vertically and horizontally polarized and the third and fourth Stokes parameters, and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>B</mi>  </mstyle></math> is the radiometer system bandwidth.

(Source: ISO 12005:2003)

