=== repeatability

stability of the response of a remote sensing instrument over time

NOTE: Repeatability or stability of a measurement between adjacent samples or within a single integrated measurement interval is referred to as "short-term" repeatability. Short-term repeatability is quantified from measurement noise with a timescale of typically seconds to minutes.

NOTE: Repeatability or stability of response from a stable input between consecutive or succeeding integrated measurement intervals is referred to as "medium-term" repeatability. Medium-term repeatability is typically quantified via benchmark tests that are included as part of a measurement sequence. Medium-term repeatability sources may include on-board stimulator sources, vicarious ground sources and stellar references. The medium-term repeatability timescale is typically minutes to hours.

NOTE: Repeatability or stability between widely separated measurement intervals is referred to as "long-term" repeatability. Long-term repeatability is typically quantified via benchmark tests that periodically measure constant radiometric source(s) over the life of the sensor. Long-term repeatability sources may include on-board stimulator sources, vicarious ground sources and stellar references. The long-term repeatability timescale is typically hours to days, up to the lifetime of the sensor.

NOTE: This entry is adapted from Reference [12].

(Source: ISO/TS 19124-1:2023)

