=== filter

<earth observation> optical device that is placed in the optical path of an Earth observation (EO) sensor to select, restrict, reject, limit or adjust an EO sensor response

NOTE: The range of desired wavelengths/frequencies to be passed by an optical filter is called the "bandpass". This is generally defined by the cut-on and cut-off wavelengths/frequencies of the optical filter.

NOTE: The EO sensor response to the optical wavelengths/frequencies within the desired optical filter bandpass is called the "in-band response".

NOTE: The ability of an optical filter (or optical system) to reject optical energy outside the desired wavelengths/frequencies is referred to as "out-of-band (OOB) blocking". This can also refer to filter design specifications regarding the ability to reject optical energy outside the desired filter bandpass.

NOTE: Undesired optical energy that passes through an optical filter (or optical system) that has a spectral location outside the desired spectral bandpass is called " OOB leakage".

NOTE: An EO sensor's response to OOB leakage is called the "OOB response".

NOTE: The ratio of the open-path throughput of an optical path with and without the filter is called transmittance". Generally expressed as a function of wavelength or optical frequency, transmittance values range from 0 to 1, or 0 % to 100 % if expressed in percent transmittance.

NOTE: This entry is adapted from Reference [12].

(Source: ISO/TS 19124-1:2023)

