=== antenna output temperature

physical temperature of correctional impedance that delivers to the receiver the same noise power as the antenna collects

NOTE: This includes two terms: the noise coming from the environment attenuated by the antenna Ohmic efficiency and the thermal noise added by the antenna Ohmic losses. In the Rayleigh-Jeans approximation, the following formula applies:<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mrow>        <mo></mo>        <mtext>A </mtext>        <mo>,</mo>        <mo></mo>        <mtext>out</mtext>      </mrow>    </msub>    <mrow>      <mo>(</mo>      <msub>        <mi>&#x3a9;</mi>        <mn>0</mn>      </msub>      <mo>)</mo>    </mrow>    <mo>=</mo>    <msub>      <mi>&#x3b7;</mi>      <mi>&#x3a9;</mi>    </msub>    <msub>      <mi>T</mi>      <mrow>        <mo></mo>        <mtext>A</mtext>      </mrow>    </msub>    <mrow>      <mo>(</mo>      <msub>        <mi>&#x3a9;</mi>        <mn>0</mn>      </msub>      <mo>)</mo>    </mrow>    <mo>+</mo>    <mrow>      <mo>(</mo>      <mn>1</mn>      <mi>−</mi>      <msub>        <mi>&#x3b7;</mi>        <mi>&#x3a9;</mi>      </msub>      <mo>)</mo>    </mrow>    <msub>      <mi>T</mi>      <mrow>        <mo></mo>        <mtext>p</mtext>      </mrow>    </msub>  </mstyle></math>

where

<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mo></mo>    </msub>    <mtext>A</mtext>  </mstyle></math> is the antenna apeture temperature;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mo></mo>    </msub>    <mtext>p</mtext>  </mstyle></math> is the physical temperature of the antenna;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>&#x3a9;</mi>      <mn>0</mn>    </msub>  </mstyle></math> is the Ohmic loss;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>&#x3b7;</mi>      <mi>&#x3a9;</mi>    </msub>  </mstyle></math> is the Ohmic efficiency of the antenna.

NOTE: The antenna output temperature (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mrow>        <mi>A</mi>        <mo>,</mo>        <mi>o</mi>        <mi>u</mi>        <mi>t</mi>      </mrow>    </msub>  </mstyle></math>) is related to the input noise temperature of the receiver as shown in the following formula: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mrow>        <mo></mo>        <mtext>rec</mtext>        <mo>,</mo>        <mo></mo>        <mtext>in</mtext>      </mrow>    </msub>    <mo>=</mo>    <mfrac>      <mrow>        <mo></mo>        <mtext>h</mtext>        <mi>&#x3bd;</mi>      </mrow>      <mrow>        <mo></mo>        <msup>          <mtext>e</mtext>          <mrow>            <mo></mo>            <mtext>h</mtext>            <mi>&#x3bd;</mi>            <mo>/</mo>            <mo></mo>            <mtext>k</mtext>            <msub>              <mi>T</mi>              <mrow>                <mi>A</mi>                <mo>,</mo>                <mo></mo>                <mtext>out</mtext>              </mrow>            </msub>          </mrow>        </msup>        <mo>&#x2212;</mo>        <mn>1</mn>      </mrow>    </mfrac>  </mstyle></math>

where

<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>T</mi>      <mrow>        <mo></mo>        <mtext>rec</mtext>        <mo>,</mo>        <mo></mo>        <mtext>in</mtext>      </mrow>    </msub>  </mstyle></math> is the input noise temperature of the receiver;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo></mo>    <mtext>h</mtext>  </mstyle></math> is the Plank's constant (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mn>6.62607</mn>    <mo>&#xd7;</mo>    <msup>      <mn>10</mn>      <mrow>        <mo>&#x2212;</mo>        <mn>34</mn>      </mrow>    </msup>    <mo></mo>    <mtext>J</mtext>    <mo>&#x22c5;</mo>    <mo></mo>    <mtext>s</mtext>  </mstyle></math>); 
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>&#x3bd;</mi>  </mstyle></math> is the frequency in Hz;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo></mo>    <mtext>k</mtext>  </mstyle></math> is the Boltzmann's constant (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mn>1.38064852</mn>    <mo>&#xd7;</mo>    <msup>      <mn>10</mn>      <mrow>        <mo>&#x2212;</mo>        <mn>23</mn>      </mrow>    </msup>    <mo></mo>    <mtext>J</mtext>    <mo>/</mo>    <mo></mo>    <mtext>K</mtext>  </mstyle></math>);
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo></mo>    <mtext>e</mtext>  </mstyle></math> is the base of natural logarithm.

(Source: ISO/TS 19159-4:2022)

