=== brightness temperature

descriptive measure of radiation in terms of the temperature (K) of a hypothetical blackbody emitting an identical amount of radiation at the same wavelength, which can be derived from the Planck's radiation law

NOTE: In the Rayleigh-Jeans limit, the microwave power per unit bandwidth received by a radiometer, <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>P</mi>  </mstyle></math>, is:

NOTE: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>P</mi>    <mo>=</mo>    <mo></mo>    <mtext>k</mtext>    <mo>&#x22c5;</mo>    <msub>      <mi>T</mi>      <mi>B</mi>    </msub>  </mstyle></math>

NOTE: where <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo></mo>    <mtext>k</mtext>  </mstyle></math> is the Boltzmann's constant (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo></mo>    <mtext>k</mtext>    <mo>=</mo>    <mn>1.38064852</mn>    <mo>&#xd7;</mo>    <msup>      <mn>10</mn>      <mrow>        <mo>&#x2212;</mo>        <mn>23</mn>      </mrow>    </msup>    <mo></mo>    <mtext>J/K</mtext>  </mstyle></math>).

NOTE: For the frequency range of microwave, Planck's radiation law can be well approximated by the Rayleigh-Jeans formula. Usually the microwave radiometers use the Rayleigh–Jeans equivalent brightness temperature, which is defined as: <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msubsup>      <mi>T</mi>      <mrow>        <mo></mo>        <mtext>b,v</mtext>      </mrow>      <mrow>        <mo></mo>        <mtext>(RJE)</mtext>      </mrow>    </msubsup>    <mo>=</mo>    <mfrac>      <msup>        <mi>c</mi>        <mn>2</mn>      </msup>      <mrow>        <mn>2</mn>        <msup>          <mi>v</mi>          <mn>2</mn>        </msup>        <mo></mo>        <mtext>k</mtext>      </mrow>    </mfrac>    <msub>      <mi>I</mi>      <mo></mo>    </msub>    <mtext>v</mtext>  </mstyle></math>

where

<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msubsup>      <mi>T</mi>      <mrow>        <mo></mo>        <mtext>b,v</mtext>      </mrow>      <mrow>        <mo></mo>        <mtext>(RJE)</mtext>      </mrow>    </msubsup>  </mstyle></math> is the Rayleigh–Jeans equivalent brightness temperature;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>v</mi>  </mstyle></math> is the frequency in Hz;
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo></mo>    <mtext>c</mtext>  </mstyle></math> is the velocity of light (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mn>2.997925</mn>    <mo>&#xd7;</mo>    <msup>      <mn>10</mn>      <mn>8</mn>    </msup>    <mo></mo>    <mtext>m</mtext>    <mo>/</mo>    <mo></mo>    <mtext>s</mtext>  </mstyle></math>);
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mo></mo>    <mtext>k</mtext>  </mstyle></math> is the Boltzmann’s constant (<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mn>1.38064852</mn>    <mo>&#xd7;</mo>    <msup>      <mn>10</mn>      <mrow>        <mo>&#x2212;</mo>        <mn>23</mn>      </mrow>    </msup>    <mo></mo>    <mtext>J</mtext>    <mo>/</mo>    <mo></mo>    <mtext>K</mtext>  </mstyle></math>);
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <msub>      <mi>I</mi>      <mo></mo>    </msub>    <mtext>v</mtext>  </mstyle></math> is the radiance.

(Source: ISO/TS 19159-4:2022)

