=== topological dimension

minimum number of free variables needed to distinguish nearby direct positions within a geometric object from one another

NOTE: The free variables mentioned above can usually be thought of as a local coordinate system. In a 3D coordinate space, a plane can be written as <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>P</mi>    <mrow>      <mo>(</mo>      <mi>u</mi>      <mo>,</mo>      <mi>v</mi>      <mo>)</mo>    </mrow>    <mo>=</mo>    <mi>A</mi>    <mo>+</mo>    <mi>u</mi>    <mi>X</mi>    <mo>+</mo>    <mi>v</mi>    <mi>Y</mi>  </mstyle></math>, where <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>u</mi>  </mstyle></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>v</mi>  </mstyle></math> are real numbers and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>A</mi>  </mstyle></math> is any point on the plane, and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>X</mi>  </mstyle></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>Y</mi>  </mstyle></math> are two vectors tangent to the plane. Since the locations on the plane can be distinguished by <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>u</mi>  </mstyle></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mi>v</mi>  </mstyle></math> (here universally), the plane is 2D and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">  <mstyle displaystyle="true">    <mrow>      <mo>(</mo>      <mi>u</mi>      <mo>,</mo>      <mi>v</mi>      <mo>)</mo>    </mrow>  </mstyle></math> is a coordinate system for the points on the plane. On generic surfaces, this cannot, in general, be done universally. If we take a plane tangent to the surface, and project points on the surface onto this plane, we will normally get a local  isomorphism for small neighbourhoods of the point of tangency. This "local coordinate" system for the underlying surface is sufficient to establish the surface as a 2D topological object. Since this International Standard deals only with spatial coordinates, any 3D object can rely on coordinates to establish its topological dimension. In a 4D model (spatio-temporal), tangent spaces also play an important role in establishing topological dimension for objects up to 3D.

(Source: ISO 19107:2003)

