=== coupling

linkage of two or more software systems through information transfer or messaging

NOTE: Compare with integration. While the conceptual schema of the information transferred shall be agreed upon to some level, coupling applications can be and are usually flexible in the data representation of that information as long as the semantics content is correct and mappable to some canonical representation of the conceptual schema. The most common mapping technology used for XML messages is XSLT, and the transformation stylesheet can be supplied either by the service broker or by the service provider. It is considered a best practice for a service provider to supply his functionality through several logically equivalent messaging APIs, each represented by a different URI linked to an XSLT transformation bridge, and implemented by the same internal code.

NOTE: Loose coupling and tight coupling are not at present well-defined terms in the literature. Generally, "tight" coupling means that there is some sort of incurred dependency between requester and responder in the use of the interface, while "loose" means no such dependency. The nature of that dependency is not consistently defined between authors.  In that light, "tight" coupling or "tight" integration are both bad practices, and have been viewed as such since the inception of the terms. Some literature refers to integration as "tight coupling", but that is a less accurate description.

(Source: ISO 19132:2007)

