=== target

object or person subject to being located

NOTE: There is little logical difference between traveller and target except that the former is normally used for a moving object which is being tracked, and the latter is used for either an object that is not moving, or an object for which a location is needed only once. A traveller is the subject of a tracking service; a target is the subject of a locating service. Since this International Standard does not make a distinction between the protocols for these logically similar services, but does need to differentiate between the two concepts, both terms will be used as appropriate to the underlying semantics of the situation. Since all of these terms refer to entities represented by objects within the system, they can be combined with adjectives defined for objects. So, an active target (a target represented by an active object) can be used to represent a moving object, since the act of motion is modifying the target's internal state and is therefore initiating actions.

(Source: ISO 19132:2007)

