== Name Assignment Policy

This section describes the name assignment policy.

=== Document types

The registers of document types http://www.opengis.net/register/ogc-na/doc-type is controlled by OGC-NA. Changes to this register (additions, deletions, and supersession) shall be initiated by a submission to the OGC Naming Authority names@opengeospatial.org.

=== Document element types

The registers of document element types is controlled by OGC-NA. Changes to this register (additions, deletions, and supersession) shall be by application to ogcna@lists.opengeospatial.org.  The current state of the register of document element types is shown at http://www.opengis.net/register/ogc-na/doc-element-type

=== Names

The register of names http://www.opengis.net/register/ogc-na/name is controlled by OGC-NA. Changes to this register (additions, deletions, and supersession) shall be initiated by a submission to the OGC Naming Authority names@opengeospatial.org.  NOTE: The approval of any new public document by OGC shall automatically trigger a registration request to OGC-NA. The name assigned shall be included on the cover page of the document.
