== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.


=== *specification*

document containing recommendations, requirements and conformance tests for those
requirements

=== *standard*

specification that has been approved by a legitimate Standards Body (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3])

=== *Web API*

API using an architectural style that is founded on the technologies of the Web http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#DWBP[DWBP]

NOTE: https://www.w3.org/TR/dwbp/#APIHttpVerbs[Best Practice 24: Use Web Standards as the foundation of APIs] in the http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#DWBP[W3C Data on the Web Best Practices] provides more detail.
