== Naming of OGC API Standards, Repositories & Specification Elements

This section presents the normative clauses of this policy. It should be noted that the clauses relating to specification elements maintain consistency with the http://portal.opengeospatial.org/files/?artifact_id=39194[OGC-NA Name type specification - specification elements (10-103)] policy.

=== Repositories

This policy document acknowledges that SWGs will create one or more Git repositories on GitHub, Gitlab or other service. To ensure consistency in the naming of Git repositories, SWGs shall be required to name the repositories as follows:

* https://github.com/opengeospatial/ogcapi-{resourceName}

The parameter {resourceName} shall be the plural of the name of the type of resource. For example, https://github.com/opengeospatial/ogcapi-features

=== Standards

Many of the emerging and existing OGC API standards are multi-part standards. This policy document acknowledges that the SWGs will have to plan to accommodate future extensions into their naming of standards. To ensure consistency in the naming of standards and their extensions, SWGs shall be required to name the standards as follows:

* OGC API - {resourceName} - Part n: {Topic}

The parameter {resourceName} shall be the plural of the name of the type of resource. 'n' refers to the position of the document in the multi-part standard and shall always be greater than zero. {Topic} refers to the topic or theme of the standard. For example, OGC API - Common - Part 1: Core

The first in the sequence of parts shall always be reserved for the 'Core' standard and therefore Part 1 is reserved for the 'Core' standard.


=== Requirements Classes

The base namespace of Requirements Classes shall indicate the Part number {n} and Version number {v} of the standard as follows.

* http://www.opengis.net/spec/ogcapi-{resourceName}-{n}/{v}/req/

For example, http://www.opengis.net/spec/ogcapi-processes-1/1.0/req/


=== Requirements

The base namespace of Requirements shall indicate the Part number {n} and Version number {v} of the standard as follows.

* http://www.opengis.net/spec/ogcapi-{resourceName}-{n}/{v}/req/

For example, http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/


=== Conformance Classes

The base namespace of Conformance Classes shall indicate the Part number {n} and Version number {v} of the standard as follows.

* http://www.opengis.net/spec/ogcapi-{resourceName}-{n}/{v}/conf/

For example, http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/

=== Abstract Tests

The base namespace of Abstract Tests shall indicate the Part number {n} and Version number {v} of the standard as follows.

* http://www.opengis.net/spec/ogcapi-{resourceName}-{n}/{v}/ats/

For example, http://www.opengis.net/spec/ogcapi-features-1/1.0/ats/
