
////
Preface sections must include [.preface] attribute
in order to get them placed in the preface area (and not in the main content).

Keywords specified in document preamble will display in this area
after the abstract
////

[abstract]
== Abstract

The mission of the OGC Naming Authority (OGC-NA) is to provide the means through which OGC resources such as OGC documents, namespaces and ontologies can be controlled and managed such that they can provide clear and well-defined names and definitions. In the terminology defined in ISO 19135, OGC-NA is the Control Body for the register of OGC Names. This document specifies a rule for constructing OGC names that may be used for identifying definitions, as well as rules for formally representing the meanings of the definitions.


[.preface]
== Preface

This document specifies a rule for constructing OGC names that may be used for identifying definitions.


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
| Name | Affiliation
|Gobe Hobona | OGC
|Simon Cox|CSIRO
|===
