[[names_for_epsg_defs]]
=== Names for EPSG definitions

http URI form:

http://www.opengis.net/def/definitionType/EPSG/0/code

URN form:

urn:ogc:def:definitionType:EPSG::code

In this case, the 'authority' part of the URI is 'EPSG'. The 'code' part of the URI is the EPSG 'code' unique identifier of the referenced definition. Alternately, the 'code' part of the URI can be the EPSG 'name' unique identifier.  In this case, omission of the version number is recommended, as this is not required to identify a referenced record in the EPSG dataset and may even lead to confusion if a version number is provided.

The policy of the Survey and Positioning Committee of the International Association of Oil and Gas Producers (IOGP) is to not delete any entities.  However, if a record is found to be incorrect, that record is deprecated and replaced. When this is done, the deprecation field of the deprecated record is changed from "false" to "true". (In some implementations, "false" may be "0" or "no", and "true" may be "1" or "yes"). Deprecated records are also termed 'invalid records'. When retrieving any geodetic parameters from the EPSG dataset a user therefore needs to verify whether the record(s) is / are valid or invalid. The user then has two options: (1) follow the links provided and use the valid replacing record(s), a course typically followed when spatially referencing a new dataset, or (2) retrieve the invalid, deprecated record(s) in order to undo the effects of this error in an existing spatial dataset that had been spatially referenced using the incorrect records. Note that spatial referencing using (an) invalid EPSG entities will only generate errors if the data is subsequently subjected to coordinate conversions and/or transformations.

*Example 1* The http URI value for EPSG CRS 3163 is:

http://www.opengis.net/def/crs/EPSG/0/3163

*Example 2* The http URI value for the "WGS 84 longitude-latitude" CRS specified in Subclause B.3 of WMS 1.3 (previously referenced as CRS:84) is:

http://www.opengis.net/def/crs/OGC/1.3/CRS84

*Example 3* The URN value for EPSG CRS 3163 is:

urn:ogc:def:crs:EPSG::3163

*Example 4* The URN value for the "WGS 84 longitude-latitude" CRS specified in Subclause B.3 of WMS 1.3 (previously referenced as "CRS:84") is:

urn:ogc:def:crs:OGC:1.3:CRS84
