[[description]]
=== Description

Each definition shall be described using the Simple Knowledge Organization System (SKOS) vocabulary of the World Wide Web (W3C) consortium. Other vocabularies may also be used *in addition* to SKOS.

The following predicates are mandatory for resources:

* *skos:prefLabel* for providing a human-readable version of a resource's name
* *dcterms:created* for stating the date the resource was created in the register
* *dcterms:modified* for stating the date the resource was modified in the register (mandatory if the resource has been modified)
* *policy:status* for indicating whether the resource is valid, retired, superseded, or under consideration
* *skos:definition* for providing a human-readable description of the resource
* *rdfs:label* for providing a human-readable version of a resource's name (used for compatibility with non-SKOS systems)

An example of a definition described in SKOS is shown below.

[%unnumbered]
[source,ttl]
----
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix policy: <http://www.opengis.net/def/metamodel/ogc-na/> .
@prefix status: <http://www.opengis.net/def/status/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://www.opengis.net/def/serviceType/ogc/wcs/2.0>
  rdf:type skos:Concept ;
  dcterms:created   "2018-03-13"^^xsd:date ;
  dcterms:modified  "2018-04-16"^^xsd:date ;
  policy:status     status:valid ;
  skos:broader <http://www.opengis.net/def/serviceType/ogc/wcs>;
  rdfs:label "OGC Web Coverage Service 2.0"^^xsd:string ;
  rdfs:seeAlso <http://www.opengis.net/spec/wcs/2.0> ;
  skos:prefLabel "OGC Web Coverage Service 2.0"@en ;
  skos:definition "A Web Coverage Service (WCS) offers multi-dimensional coverage data for access over the Internet" .

----
