[[name_assignment]]
== Name Assignment and Resolution

This section describes the name assignment policy.

=== Definition types

The register of definition types http://www.opengis.net/register/ogc-na/def-type is controlled by OGC-NA. Changes to this register (additions, deletions, and supersession) shall be initiated by a submission to the OGC Naming Authority names@opengeospatial.org.

=== Authorities

The register of authorities http://www.opengis.net/register/ogc-na/authority is controlled by OGC-NA. Changes to this register (additions, deletions, and supersession) shall be initiated by a submission to the OGC Naming Authority names@opengeospatial.org.

=== Names

The register of names http://www.opengis.net/def/ is controlled by OGC-NA. Changes to this register (addition, deletion, and supersession) shall be initiated by a submission to the OGC Naming Authority names@opengeospatial.org.

=== Names for EPSG definitions

http URI form:

http://www.opengis.net/def/definitionType/EPSG/0/code

URN form:

urn:ogc:def:definitionType:EPSG::code

In this case, the 'authority' part of the URI is 'EPSG'. The 'code' part of the URI is the EPSG 'code' unique identifier of the referenced definition. Alternately, the 'code' part of the URI can be the EPSG 'name' unique identifier.  In this case, omission of the version number is recommended, as this is not required to identify a referenced record in the EPSG dataset and may even lead to confusion if a version number is provided.

The policy of the Survey and Positioning Committee of the International Association of Oil and Gas Producers (IOGP) is to not delete any entities.  However, if a record is found to be incorrect, that record is deprecated and replaced. When this is done, the deprecation field of the deprecated record is changed from "false" to "true". (In some implementations, "false" may be "0" or "no", and "true" may be "1" or "yes"). Deprecated records are also termed 'invalid records'. When retrieving any geodetic parameters from the EPSG dataset a user therefore needs to verify whether the record(s) is / are valid or invalid. The user then has two options: (1) follow the links provided and use the valid replacing record(s), a course typically followed when spatially referencing a new dataset, or (2) retrieve the invalid, deprecated record(s) in order to undo the effects of this error in an existing spatial dataset that had been spatially referenced using the incorrect records. Note that spatial referencing using (an) invalid EPSG entities will only generate errors if the data is subsequently subjected to coordinate conversions and/or transformations.

Example 1 The http URI value for EPSG CRS 3163 is:

http://www.opengis.net/def/crs/EPSG/0/3163

Example 2 The http URI value for the "WGS 84 longitude-latitude" CRS specified in Subclause B.3 of WMS 1.3 (previously referenced as CRS:84) is:

http://www.opengis.net/def/crs/OGC/1.3/CRS84

Example 3 The URN value for EPSG CRS 3163 is:

urn:ogc:def:crs:EPSG::3163

Example 4 The URN value for the "WGS 84 longitude-latitude" CRS specified in Subclause B.3 of WMS 1.3 (previously referenced as "CRS:84") is:

urn:ogc:def:crs:OGC:1.3:CRS84


=== Description

Each definition shall be described using the Simple Knowledge Organization System (SKOS) vocabulary of the World Wide Web (W3C) consortium. Other vocabularies may also be used *in addition* to SKOS.

The following predicates are mandatory for resources:

* *skos:prefLabel* for providing a human-readable version of a resource's name
* *dcterms:created* for stating the date the resource was created in the register
* *dcterms:modified* for stating the date the resource was modified in the register (mandatory if the resource has been modified)
* *policy:status* for indicating whether the resource is valid, retired, superseded, or under consideration
* *skos:definition* for providing a human-readable description of the resource
* *rdfs:label* for providing a human-readable version of a resource's name (used for compatibility with non-SKOS systems)

An example of a definition described in SKOS is shown below.

[%unnumbered]
[source,ttl]
----
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix policy: <http://www.opengis.net/def/metamodel/ogc-na/> .
@prefix status: <http://www.opengis.net/def/status/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://www.opengis.net/def/serviceType/ogc/wcs/2.0>
  rdf:type skos:Concept ;
  dcterms:created   "2018-03-13"^^xsd:date ;
  dcterms:modified  "2018-04-16"^^xsd:date ;
  policy:status     status:valid ;
  skos:broader <http://www.opengis.net/def/serviceType/ogc/wcs>;
  rdfs:label "OGC Web Coverage Service 2.0"^^xsd:string ;
  rdfs:seeAlso <http://www.opengis.net/spec/wcs/2.0> ;
  skos:prefLabel "OGC Web Coverage Service 2.0"@en ;
  skos:definition "A Web Coverage Service (WCS) offers multi-dimensional coverage data for access over the Internet" .

----

=== Resolution of the Same Definition to Different Encodings

The definition of a resource may be accessed in any number of encodings that are supported by a resolution service or resolver. A resolution service and a client application shall negotiate the encoding format to use through the content negotiation process defined in http://docs.ogc.org/DRAFTS/19-072.html#rfc7231[IETF RFC 7231]. A non-exhaustive list of example encodings relevant to different resources is below:

* Geography Markup Language (GML): Supports the encoding on features, coordinate reference systems, and codelists.
* Well Known Text (WKT): Supports the encoding on features, and coordinate reference systems.
* Simple Knowledge Organization System (SKOS) in Resource Description Framework (RDF): Supports the encoding concepts, glossaries, and thesauri

=== Assigning and Handling Name Aliases

Where the URI of a named resource has an alias, the OGC-NA shall entail copies of all the properties for both forms of URI, and create inverse https://www.w3.org/TR/owl-ref/#sameAs-def[sameAs] relationships. For example, upon registering the resource `example-B` as an alias of `example-A`,

* all of the properties of  `example-A` shall be copied to `example-B`
* the statement that `example-B` is sameAs `example-A` shall be declared
* the statement that `example-A` is sameAs `example-B` shall be declared
