name: Batch manual entail, no database update
on:
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo
        uses: actions/checkout@v2
      - name: install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - name: batch process all entailments and validations
        run: |
          echo 'Run batch update script...'
          python scripts/update_vocabs.py -b -d definitions/conceptschemes
      - name: commit new generated files for entailments and validations
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: .
          message: "Batch Generated entailment and validation results and serialisations"
          default_author: github_actions
