name: SWG - Doc matching
on:
  schedule:
    - cron: '30 3 */4 * *'
  workflow_dispatch:
jobs:
  download-and-match:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Perform matching
        env:
          SWGDOCMATCH_GS_URL: ${{ secrets.SWGDOCMATCH_GS_URL }}
        run: pip install rdflib && python scripts/swgdocmatch.py
      - name: Commit new versions of files
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: "SWG - doc matching"
          default_author: github_actions
    outputs:
      has-changes: ${{ steps.commit.outputs.committed }}

  call-entail-validate-changes-workflow:
    needs: download-and-match
    if: needs.download-and-match.outputs.has-changes == 'true'
    uses: ./.github/workflows/entail_and_validate_changes.yml
    secrets: inherit
    with:
      files-modified: incubation/working-groups/docs.ttl
      repo-ref: ${{ github.ref_name }}
